package com.t.zero.message.platform.model.auto;

import java.io.Serializable;
import java.time.LocalDateTime;

public class RelUserMessageScene implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_rel_user_message_scene.id
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_rel_user_message_scene.user_id
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_rel_user_message_scene.scene_id
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    private Integer sceneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_rel_user_message_scene.scene_code
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    private String sceneCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_rel_user_message_scene.rel_status
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    private Byte relStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_rel_user_message_scene.created_user_id
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_rel_user_message_scene.created_time
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    private LocalDateTime createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_zero_rel_user_message_scene
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_rel_user_message_scene.id
     *
     * @return the value of t_zero_rel_user_message_scene.id
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_rel_user_message_scene.id
     *
     * @param id the value for t_zero_rel_user_message_scene.id
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_rel_user_message_scene.user_id
     *
     * @return the value of t_zero_rel_user_message_scene.user_id
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_rel_user_message_scene.user_id
     *
     * @param userId the value for t_zero_rel_user_message_scene.user_id
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_rel_user_message_scene.scene_id
     *
     * @return the value of t_zero_rel_user_message_scene.scene_id
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    public Integer getSceneId() {
        return sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_rel_user_message_scene.scene_id
     *
     * @param sceneId the value for t_zero_rel_user_message_scene.scene_id
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    public void setSceneId(Integer sceneId) {
        this.sceneId = sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_rel_user_message_scene.scene_code
     *
     * @return the value of t_zero_rel_user_message_scene.scene_code
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    public String getSceneCode() {
        return sceneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_rel_user_message_scene.scene_code
     *
     * @param sceneCode the value for t_zero_rel_user_message_scene.scene_code
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    public void setSceneCode(String sceneCode) {
        this.sceneCode = sceneCode == null ? null : sceneCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_rel_user_message_scene.rel_status
     *
     * @return the value of t_zero_rel_user_message_scene.rel_status
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    public Byte getRelStatus() {
        return relStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_rel_user_message_scene.rel_status
     *
     * @param relStatus the value for t_zero_rel_user_message_scene.rel_status
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    public void setRelStatus(Byte relStatus) {
        this.relStatus = relStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_rel_user_message_scene.created_user_id
     *
     * @return the value of t_zero_rel_user_message_scene.created_user_id
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_rel_user_message_scene.created_user_id
     *
     * @param createdUserId the value for t_zero_rel_user_message_scene.created_user_id
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zero_rel_user_message_scene.created_time
     *
     * @return the value of t_zero_rel_user_message_scene.created_time
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zero_rel_user_message_scene.created_time
     *
     * @param createdTime the value for t_zero_rel_user_message_scene.created_time
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_rel_user_message_scene
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", sceneId=").append(sceneId);
        sb.append(", sceneCode=").append(sceneCode);
        sb.append(", relStatus=").append(relStatus);
        sb.append(", createdUserId=").append(createdUserId);
        sb.append(", createdTime=").append(createdTime);
        sb.append("]");
        return sb.toString();
    }
}