package com.t.zero.rpc.user.api.bean;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.JsonNode;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;


@JsonInclude(JsonInclude.Include.NON_NULL)
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
@Data
public class GroupDefinedVo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_group_defined.id
     *
     * @mbg.generated Fri Jul 02 12:14:33 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_group_defined.tenant_id
     *
     * @mbg.generated Fri Jul 02 12:14:33 CST 2021
     */
    private Integer tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_group_defined.group_code
     *
     * @mbg.generated Fri Jul 02 12:14:33 CST 2021
     */
    private String groupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_group_defined.group_name
     *
     * @mbg.generated Fri Jul 02 12:14:33 CST 2021
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_group_defined.parent_group_id
     *
     * @mbg.generated Fri Jul 02 12:14:33 CST 2021
     */
    private Integer parentGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_group_defined.parent_group_code
     *
     * @mbg.generated Fri Jul 02 12:14:33 CST 2021
     */
    private String parentGroupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_group_defined.group_parants
     *
     * @mbg.generated Fri Jul 02 12:14:33 CST 2021
     */
    private String groupParants;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_group_defined.group_status
     *
     * @mbg.generated Fri Jul 02 12:14:33 CST 2021
     */
    private Byte groupStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_group_defined.created_user_id
     *
     * @mbg.generated Fri Jul 02 12:14:33 CST 2021
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_group_defined.created_time
     *
     * @mbg.generated Fri Jul 02 12:14:33 CST 2021
     */
    private LocalDateTime createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_group_defined.updated_user_id
     *
     * @mbg.generated Fri Jul 02 12:14:33 CST 2021
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_group_defined.updated_time
     *
     * @mbg.generated Fri Jul 02 12:14:33 CST 2021
     */
    private LocalDateTime updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_group_defined.is_deleted
     *
     * @mbg.generated Fri Jul 02 12:14:33 CST 2021
     */
    private String deletedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zero_group_defined.group_desc
     *
     * @mbg.generated Fri Jul 02 12:14:33 CST 2021
     */
    private JsonNode groupDesc;


    private ServiceAccountStatisticsVo statisticsVo;


    private Map<String, ServiceAccountStatisticsVo> accoutMap;

    private Boolean canOperate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_zero_group_defined
     *
     * @mbg.generated Fri Jul 02 12:14:33 CST 2021
     */
    private static final long serialVersionUID = 1L;


}