package com.t.zero.rpc.user.api.bean;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonInclude;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

@JsonInclude(JsonInclude.Include.NON_NULL) 
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
@Data
public class UserInfo implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2365049913520598533L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_user_info.id
	 *
	 * @mbg.generated Fri Jun 25 20:50:48 CST 2021
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_user_info.user_code
	 *
	 * @mbg.generated Fri Jun 25 20:50:48 CST 2021
	 */
	private String userCode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_user_info.tenant_id
	 *
	 * @mbg.generated Fri Jun 25 20:50:48 CST 2021
	 */
	private Integer tenantId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_user_info.username
	 *
	 * @mbg.generated Fri Jun 25 20:50:48 CST 2021
	 */
	private String username;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_user_info.nick_name
	 *
	 * @mbg.generated Fri Jun 25 20:50:48 CST 2021
	 */
	private String nickName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_user_info.phone_number
	 *
	 * @mbg.generated Fri Jun 25 20:50:48 CST 2021
	 */
	private String phoneNumber;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_user_info.email_address
	 *
	 * @mbg.generated Fri Jun 25 20:50:48 CST 2021
	 */
	private String emailAddress;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_user_info.user_status
	 *
	 * @mbg.generated Fri Jun 25 20:50:48 CST 2021
	 */
	private Byte userStatus;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_zero_user_info.is_deleted
	 *
	 * @mbg.generated Fri Jun 25 20:50:48 CST 2021
	 */
	private String deletedFlag;

}
