package com.t.zero.b.i.pump.db.dao.auto;

import com.t.zero.b.i.pump.db.model.auto.InfoTotalCache;
import com.t.zero.b.i.pump.db.model.auto.InfoTotalCacheExample;
import java.time.LocalDateTime;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InfoTotalCacheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_total_cache
     *
     * @mbg.generated Sat May 20 10:45:18 CST 2023
     */
    long countByExample(InfoTotalCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_total_cache
     *
     * @mbg.generated Sat May 20 10:45:18 CST 2023
     */
    int deleteByExample(InfoTotalCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_total_cache
     *
     * @mbg.generated Sat May 20 10:45:18 CST 2023
     */
    int deleteByPrimaryKey(LocalDateTime ts);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_total_cache
     *
     * @mbg.generated Sat May 20 10:45:18 CST 2023
     */
    int insert(InfoTotalCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_total_cache
     *
     * @mbg.generated Sat May 20 10:45:18 CST 2023
     */
    int insertSelective(InfoTotalCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_total_cache
     *
     * @mbg.generated Sat May 20 10:45:18 CST 2023
     */
    List<InfoTotalCache> selectByExample(InfoTotalCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_total_cache
     *
     * @mbg.generated Sat May 20 10:45:18 CST 2023
     */
    InfoTotalCache selectByPrimaryKey(LocalDateTime ts);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_total_cache
     *
     * @mbg.generated Sat May 20 10:45:18 CST 2023
     */
    int updateByExampleSelective(@Param("record") InfoTotalCache record, @Param("example") InfoTotalCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_total_cache
     *
     * @mbg.generated Sat May 20 10:45:18 CST 2023
     */
    int updateByExample(@Param("record") InfoTotalCache record, @Param("example") InfoTotalCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_total_cache
     *
     * @mbg.generated Sat May 20 10:45:18 CST 2023
     */
    int updateByPrimaryKeySelective(InfoTotalCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_total_cache
     *
     * @mbg.generated Sat May 20 10:45:18 CST 2023
     */
    int updateByPrimaryKey(InfoTotalCache record);
}