package com.t.zero.b.i.pump.db.dao.auto;

import com.t.zero.b.i.pump.db.model.auto.ProjectHeader;
import com.t.zero.b.i.pump.db.model.auto.ProjectHeaderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectHeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectheader
     *
     * @mbg.generated Sat Feb 25 10:41:32 CST 2023
     */
    long countByExample(ProjectHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectheader
     *
     * @mbg.generated Sat Feb 25 10:41:32 CST 2023
     */
    int deleteByExample(ProjectHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectheader
     *
     * @mbg.generated Sat Feb 25 10:41:32 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectheader
     *
     * @mbg.generated Sat Feb 25 10:41:32 CST 2023
     */
    int insert(ProjectHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectheader
     *
     * @mbg.generated Sat Feb 25 10:41:32 CST 2023
     */
    int insertSelective(ProjectHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectheader
     *
     * @mbg.generated Sat Feb 25 10:41:32 CST 2023
     */
    List<ProjectHeader> selectByExample(ProjectHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectheader
     *
     * @mbg.generated Sat Feb 25 10:41:32 CST 2023
     */
    ProjectHeader selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectheader
     *
     * @mbg.generated Sat Feb 25 10:41:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") ProjectHeader record, @Param("example") ProjectHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectheader
     *
     * @mbg.generated Sat Feb 25 10:41:32 CST 2023
     */
    int updateByExample(@Param("record") ProjectHeader record, @Param("example") ProjectHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectheader
     *
     * @mbg.generated Sat Feb 25 10:41:32 CST 2023
     */
    int updateByPrimaryKeySelective(ProjectHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectheader
     *
     * @mbg.generated Sat Feb 25 10:41:32 CST 2023
     */
    int updateByPrimaryKey(ProjectHeader record);
}