package com.t.zero.b.i.pump.db.dao.auto;

import com.t.zero.b.i.pump.db.model.auto.PumpExportDxfTemplate;
import com.t.zero.b.i.pump.db.model.auto.PumpExportDxfTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PumpExportDxfTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_export_dxf_template
     *
     * @mbg.generated Sat May 20 10:45:17 CST 2023
     */
    long countByExample(PumpExportDxfTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_export_dxf_template
     *
     * @mbg.generated Sat May 20 10:45:17 CST 2023
     */
    int deleteByExample(PumpExportDxfTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_export_dxf_template
     *
     * @mbg.generated Sat May 20 10:45:17 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_export_dxf_template
     *
     * @mbg.generated Sat May 20 10:45:17 CST 2023
     */
    int insert(PumpExportDxfTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_export_dxf_template
     *
     * @mbg.generated Sat May 20 10:45:17 CST 2023
     */
    int insertSelective(PumpExportDxfTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_export_dxf_template
     *
     * @mbg.generated Sat May 20 10:45:17 CST 2023
     */
    List<PumpExportDxfTemplate> selectByExampleWithBLOBs(PumpExportDxfTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_export_dxf_template
     *
     * @mbg.generated Sat May 20 10:45:17 CST 2023
     */
    List<PumpExportDxfTemplate> selectByExample(PumpExportDxfTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_export_dxf_template
     *
     * @mbg.generated Sat May 20 10:45:17 CST 2023
     */
    PumpExportDxfTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_export_dxf_template
     *
     * @mbg.generated Sat May 20 10:45:17 CST 2023
     */
    int updateByExampleSelective(@Param("record") PumpExportDxfTemplate record, @Param("example") PumpExportDxfTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_export_dxf_template
     *
     * @mbg.generated Sat May 20 10:45:17 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") PumpExportDxfTemplate record, @Param("example") PumpExportDxfTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_export_dxf_template
     *
     * @mbg.generated Sat May 20 10:45:17 CST 2023
     */
    int updateByExample(@Param("record") PumpExportDxfTemplate record, @Param("example") PumpExportDxfTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_export_dxf_template
     *
     * @mbg.generated Sat May 20 10:45:17 CST 2023
     */
    int updateByPrimaryKeySelective(PumpExportDxfTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_export_dxf_template
     *
     * @mbg.generated Sat May 20 10:45:17 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(PumpExportDxfTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_export_dxf_template
     *
     * @mbg.generated Sat May 20 10:45:17 CST 2023
     */
    int updateByPrimaryKey(PumpExportDxfTemplate record);
}