package com.t.zero.b.i.pump.db.dao.auto;

import com.t.zero.b.i.pump.db.model.auto.PumpForcesAndMoments;
import com.t.zero.b.i.pump.db.model.auto.PumpForcesAndMomentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PumpForcesAndMomentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_forces_and_moments
     *
     * @mbg.generated Sat Jan 14 17:17:13 CST 2023
     */
    long countByExample(PumpForcesAndMomentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_forces_and_moments
     *
     * @mbg.generated Sat Jan 14 17:17:13 CST 2023
     */
    int deleteByExample(PumpForcesAndMomentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_forces_and_moments
     *
     * @mbg.generated Sat Jan 14 17:17:13 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_forces_and_moments
     *
     * @mbg.generated Sat Jan 14 17:17:13 CST 2023
     */
    int insert(PumpForcesAndMoments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_forces_and_moments
     *
     * @mbg.generated Sat Jan 14 17:17:13 CST 2023
     */
    int insertSelective(PumpForcesAndMoments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_forces_and_moments
     *
     * @mbg.generated Sat Jan 14 17:17:13 CST 2023
     */
    List<PumpForcesAndMoments> selectByExampleWithBLOBs(PumpForcesAndMomentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_forces_and_moments
     *
     * @mbg.generated Sat Jan 14 17:17:13 CST 2023
     */
    List<PumpForcesAndMoments> selectByExample(PumpForcesAndMomentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_forces_and_moments
     *
     * @mbg.generated Sat Jan 14 17:17:13 CST 2023
     */
    PumpForcesAndMoments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_forces_and_moments
     *
     * @mbg.generated Sat Jan 14 17:17:13 CST 2023
     */
    int updateByExampleSelective(@Param("record") PumpForcesAndMoments record, @Param("example") PumpForcesAndMomentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_forces_and_moments
     *
     * @mbg.generated Sat Jan 14 17:17:13 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") PumpForcesAndMoments record, @Param("example") PumpForcesAndMomentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_forces_and_moments
     *
     * @mbg.generated Sat Jan 14 17:17:13 CST 2023
     */
    int updateByExample(@Param("record") PumpForcesAndMoments record, @Param("example") PumpForcesAndMomentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_forces_and_moments
     *
     * @mbg.generated Sat Jan 14 17:17:13 CST 2023
     */
    int updateByPrimaryKeySelective(PumpForcesAndMoments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_forces_and_moments
     *
     * @mbg.generated Sat Jan 14 17:17:13 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(PumpForcesAndMoments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_forces_and_moments
     *
     * @mbg.generated Sat Jan 14 17:17:13 CST 2023
     */
    int updateByPrimaryKey(PumpForcesAndMoments record);
}