package com.t.zero.b.i.pump.db.dao.auto;

import com.t.zero.b.i.pump.db.model.auto.PumpArchitectureInfo;
import com.t.zero.b.i.pump.db.model.auto.PumpArchitectureInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PumpArchitectureInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_architecture_info
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    long countByExample(PumpArchitectureInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_architecture_info
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    int deleteByExample(PumpArchitectureInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_architecture_info
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_architecture_info
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    int insert(PumpArchitectureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_architecture_info
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    int insertSelective(PumpArchitectureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_architecture_info
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    List<PumpArchitectureInfo> selectByExampleWithBLOBs(PumpArchitectureInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_architecture_info
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    List<PumpArchitectureInfo> selectByExample(PumpArchitectureInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_architecture_info
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    PumpArchitectureInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_architecture_info
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    int updateByExampleSelective(@Param("record") PumpArchitectureInfo record, @Param("example") PumpArchitectureInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_architecture_info
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") PumpArchitectureInfo record, @Param("example") PumpArchitectureInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_architecture_info
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    int updateByExample(@Param("record") PumpArchitectureInfo record, @Param("example") PumpArchitectureInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_architecture_info
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    int updateByPrimaryKeySelective(PumpArchitectureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_architecture_info
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(PumpArchitectureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_architecture_info
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    int updateByPrimaryKey(PumpArchitectureInfo record);
}