package com.t.zero.message.platform.dao.auto;

import com.t.zero.message.platform.model.auto.ChannelInstance;
import com.t.zero.message.platform.model.auto.ChannelInstanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_instance
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    long countByExample(ChannelInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_instance
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int deleteByExample(ChannelInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_instance
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_instance
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int insert(ChannelInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_instance
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int insertSelective(ChannelInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_instance
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    List<ChannelInstance> selectByExample(ChannelInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_instance
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    ChannelInstance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_instance
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") ChannelInstance record, @Param("example") ChannelInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_instance
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByExample(@Param("record") ChannelInstance record, @Param("example") ChannelInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_instance
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByPrimaryKeySelective(ChannelInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_instance
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByPrimaryKey(ChannelInstance record);
}