package com.t.zero.message.platform.dao.auto;

import com.t.zero.message.platform.model.auto.ChannelDefined;
import com.t.zero.message.platform.model.auto.ChannelDefinedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelDefinedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_defined
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    long countByExample(ChannelDefinedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_defined
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int deleteByExample(ChannelDefinedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_defined
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_defined
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int insert(ChannelDefined record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_defined
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int insertSelective(ChannelDefined record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_defined
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    List<ChannelDefined> selectByExampleWithBLOBs(ChannelDefinedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_defined
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    List<ChannelDefined> selectByExample(ChannelDefinedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_defined
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    ChannelDefined selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_defined
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") ChannelDefined record, @Param("example") ChannelDefinedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_defined
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") ChannelDefined record, @Param("example") ChannelDefinedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_defined
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByExample(@Param("record") ChannelDefined record, @Param("example") ChannelDefinedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_defined
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByPrimaryKeySelective(ChannelDefined record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_defined
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(ChannelDefined record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_channel_defined
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByPrimaryKey(ChannelDefined record);
}