package com.t.zero.message.platform.dao.auto;

import com.t.zero.message.platform.model.auto.FileDescription;
import com.t.zero.message.platform.model.auto.FileDescriptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileDescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_file_description
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    long countByExample(FileDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_file_description
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int deleteByExample(FileDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_file_description
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_file_description
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int insert(FileDescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_file_description
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int insertSelective(FileDescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_file_description
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    List<FileDescription> selectByExampleWithBLOBs(FileDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_file_description
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    List<FileDescription> selectByExample(FileDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_file_description
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    FileDescription selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_file_description
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") FileDescription record, @Param("example") FileDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_file_description
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") FileDescription record, @Param("example") FileDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_file_description
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByExample(@Param("record") FileDescription record, @Param("example") FileDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_file_description
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByPrimaryKeySelective(FileDescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_file_description
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(FileDescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_file_description
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByPrimaryKey(FileDescription record);
}