package com.t.zero.message.platform.dao.auto;

import com.t.zero.message.platform.model.auto.MessageTemplate;
import com.t.zero.message.platform.model.auto.MessageTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_template
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    long countByExample(MessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_template
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int deleteByExample(MessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_template
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_template
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int insert(MessageTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_template
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int insertSelective(MessageTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_template
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    List<MessageTemplate> selectByExampleWithBLOBs(MessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_template
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    List<MessageTemplate> selectByExample(MessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_template
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    MessageTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_template
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") MessageTemplate record, @Param("example") MessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_template
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") MessageTemplate record, @Param("example") MessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_template
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByExample(@Param("record") MessageTemplate record, @Param("example") MessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_template
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByPrimaryKeySelective(MessageTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_template
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(MessageTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_template
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByPrimaryKey(MessageTemplate record);
}