package com.t.zero.message.platform.dao.auto;

import com.t.zero.message.platform.model.auto.MessageScene;
import com.t.zero.message.platform.model.auto.MessageSceneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageSceneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_scene
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    long countByExample(MessageSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_scene
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int deleteByExample(MessageSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_scene
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_scene
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int insert(MessageScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_scene
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int insertSelective(MessageScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_scene
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    List<MessageScene> selectByExample(MessageSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_scene
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    MessageScene selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_scene
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") MessageScene record, @Param("example") MessageSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_scene
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByExample(@Param("record") MessageScene record, @Param("example") MessageSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_scene
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByPrimaryKeySelective(MessageScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zero_message_scene
     *
     * @mbg.generated Tue Jul 27 18:33:33 CST 2021
     */
    int updateByPrimaryKey(MessageScene record);
}