package com.t.zero.message.platform.vo.request;

import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.JsonNode;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

@JsonInclude(JsonInclude.Include.NON_NULL) 
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
@Data
public class ChannelDefinedVo {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_channel_defined.id
    *
    * @mbg.generated Wed Jun 30 11:03:01 CST 2021
    */
   private Integer id;
   
   private Integer userId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_channel_defined.tenant_id
    *
    * @mbg.generated Wed Jun 30 11:03:01 CST 2021
    */
   private Integer tenantId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_channel_defined.channel_code
    *
    * @mbg.generated Wed Jun 30 11:03:01 CST 2021
    */
   private String channelCode;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_channel_defined.channel_type
    *
    * @mbg.generated Wed Jun 30 11:03:01 CST 2021
    */
   private String channelType;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_channel_defined.channel_name
    *
    * @mbg.generated Wed Jun 30 11:03:01 CST 2021
    */
   private String channelName;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_channel_defined.channel_default
    *
    * @mbg.generated Wed Jun 30 11:03:01 CST 2021
    */
   private Byte channelDefault;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_channel_defined.demand_status
    *
    * @mbg.generated Wed Jun 30 11:03:01 CST 2021
    */
   private Byte channelStatus;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_channel_defined.created_user_id
    *
    * @mbg.generated Wed Jun 30 11:03:01 CST 2021
    */
   private String createdUserId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_channel_defined.created_time
    *
    * @mbg.generated Wed Jun 30 11:03:01 CST 2021
    */
   private LocalDateTime createdTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_channel_defined.updated_user_id
    *
    * @mbg.generated Wed Jun 30 11:03:01 CST 2021
    */
   private String updatedUserId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_channel_defined.updated_time
    *
    * @mbg.generated Wed Jun 30 11:03:01 CST 2021
    */
   private LocalDateTime updatedTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_channel_defined.is_deleted
    *
    * @mbg.generated Wed Jun 30 11:03:01 CST 2021
    */
   private String deletedFlag;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_channel_defined.channel_desc
    *
    * @mbg.generated Wed Jun 30 11:03:01 CST 2021
    */
   private JsonNode channelDesc;

}
