package com.t.zero.message.platform.vo.request;

import java.time.LocalDateTime;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.JsonNode;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

@JsonInclude(JsonInclude.Include.NON_NULL) 
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
@Data
public class MessageInstanceVo {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_message_instance.id
    *
    * @mbg.generated Wed Jun 30 21:16:12 CST 2021
    */
   private Integer id;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_message_instance.user_id
    *
    * @mbg.generated Wed Jun 30 21:16:12 CST 2021
    */
   private Integer userId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_message_instance.product_id
    *
    * @mbg.generated Wed Jun 30 21:16:12 CST 2021
    */
   private Integer productId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_message_instance.business_type
    *
    * @mbg.generated Wed Jun 30 21:16:12 CST 2021
    */
   private String businessType;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_message_instance.template_id
    *
    * @mbg.generated Wed Jun 30 21:16:12 CST 2021
    */
   private Integer templateId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_message_instance.channel_code
    *
    * @mbg.generated Wed Jun 30 21:16:12 CST 2021
    */
   private String channelCode;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_message_instance.send_status
    *
    * @mbg.generated Wed Jun 30 21:16:12 CST 2021
    */
   private Byte sendStatus;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_message_instance.readed_flag
    *
    * @mbg.generated Wed Jun 30 21:16:12 CST 2021
    */
   private Byte readedFlag;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_message_instance.created_user_id
    *
    * @mbg.generated Wed Jun 30 21:16:12 CST 2021
    */
   private String createdUserId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_message_instance.created_time
    *
    * @mbg.generated Wed Jun 30 21:16:12 CST 2021
    */
   private LocalDateTime createdTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_message_instance.updated_user_id
    *
    * @mbg.generated Wed Jun 30 21:16:12 CST 2021
    */
   private String updatedUserId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_message_instance.updated_time
    *
    * @mbg.generated Wed Jun 30 21:16:12 CST 2021
    */
   private LocalDateTime updatedTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_message_instance.is_deleted
    *
    * @mbg.generated Wed Jun 30 21:16:12 CST 2021
    */
   private String deletedFlag;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_zero_message_instance.message_content
    *
    * @mbg.generated Wed Jun 30 21:16:12 CST 2021
    */
   private JsonNode messageContent;

   private List<Integer> messageIds;
}
