package com.t.zero.b.i.pump.db.model.auto;

import java.io.Serializable;

public class ProjectInfoWithBLOBs extends ProjectInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.pv_desc
     *
     * @mbg.generated Tue Apr 11 19:11:33 CST 2023
     */
    private String pvDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.additions
     *
     * @mbg.generated Tue Apr 11 19:11:33 CST 2023
     */
    private String additions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table projectinfo
     *
     * @mbg.generated Tue Apr 11 19:11:33 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.pv_desc
     *
     * @return the value of projectinfo.pv_desc
     *
     * @mbg.generated Tue Apr 11 19:11:33 CST 2023
     */
    public String getPvDesc() {
        return pvDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.pv_desc
     *
     * @param pvDesc the value for projectinfo.pv_desc
     *
     * @mbg.generated Tue Apr 11 19:11:33 CST 2023
     */
    public void setPvDesc(String pvDesc) {
        this.pvDesc = pvDesc == null ? null : pvDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.additions
     *
     * @return the value of projectinfo.additions
     *
     * @mbg.generated Tue Apr 11 19:11:33 CST 2023
     */
    public String getAdditions() {
        return additions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.additions
     *
     * @param additions the value for projectinfo.additions
     *
     * @mbg.generated Tue Apr 11 19:11:33 CST 2023
     */
    public void setAdditions(String additions) {
        this.additions = additions == null ? null : additions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbg.generated Tue Apr 11 19:11:33 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pvDesc=").append(pvDesc);
        sb.append(", additions=").append(additions);
        sb.append("]");
        return sb.toString();
    }
}