package com.t.zero.b.i.pump.db.model.auto;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PumpInformationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    public PumpInformationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPvCodeIsNull() {
            addCriterion("pv_code is null");
            return (Criteria) this;
        }

        public Criteria andPvCodeIsNotNull() {
            addCriterion("pv_code is not null");
            return (Criteria) this;
        }

        public Criteria andPvCodeEqualTo(String value) {
            addCriterion("pv_code =", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeNotEqualTo(String value) {
            addCriterion("pv_code <>", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeGreaterThan(String value) {
            addCriterion("pv_code >", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeGreaterThanOrEqualTo(String value) {
            addCriterion("pv_code >=", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeLessThan(String value) {
            addCriterion("pv_code <", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeLessThanOrEqualTo(String value) {
            addCriterion("pv_code <=", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeLike(String value) {
            addCriterion("pv_code like", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeNotLike(String value) {
            addCriterion("pv_code not like", value, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeIn(List<String> values) {
            addCriterion("pv_code in", values, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeNotIn(List<String> values) {
            addCriterion("pv_code not in", values, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeBetween(String value1, String value2) {
            addCriterion("pv_code between", value1, value2, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPvCodeNotBetween(String value1, String value2) {
            addCriterion("pv_code not between", value1, value2, "pvCode");
            return (Criteria) this;
        }

        public Criteria andPumpBusiIdIsNull() {
            addCriterion("pump_busi_id is null");
            return (Criteria) this;
        }

        public Criteria andPumpBusiIdIsNotNull() {
            addCriterion("pump_busi_id is not null");
            return (Criteria) this;
        }

        public Criteria andPumpBusiIdEqualTo(Integer value) {
            addCriterion("pump_busi_id =", value, "pumpBusiId");
            return (Criteria) this;
        }

        public Criteria andPumpBusiIdNotEqualTo(Integer value) {
            addCriterion("pump_busi_id <>", value, "pumpBusiId");
            return (Criteria) this;
        }

        public Criteria andPumpBusiIdGreaterThan(Integer value) {
            addCriterion("pump_busi_id >", value, "pumpBusiId");
            return (Criteria) this;
        }

        public Criteria andPumpBusiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pump_busi_id >=", value, "pumpBusiId");
            return (Criteria) this;
        }

        public Criteria andPumpBusiIdLessThan(Integer value) {
            addCriterion("pump_busi_id <", value, "pumpBusiId");
            return (Criteria) this;
        }

        public Criteria andPumpBusiIdLessThanOrEqualTo(Integer value) {
            addCriterion("pump_busi_id <=", value, "pumpBusiId");
            return (Criteria) this;
        }

        public Criteria andPumpBusiIdIn(List<Integer> values) {
            addCriterion("pump_busi_id in", values, "pumpBusiId");
            return (Criteria) this;
        }

        public Criteria andPumpBusiIdNotIn(List<Integer> values) {
            addCriterion("pump_busi_id not in", values, "pumpBusiId");
            return (Criteria) this;
        }

        public Criteria andPumpBusiIdBetween(Integer value1, Integer value2) {
            addCriterion("pump_busi_id between", value1, value2, "pumpBusiId");
            return (Criteria) this;
        }

        public Criteria andPumpBusiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pump_busi_id not between", value1, value2, "pumpBusiId");
            return (Criteria) this;
        }

        public Criteria andPumpNameIsNull() {
            addCriterion("pump_name is null");
            return (Criteria) this;
        }

        public Criteria andPumpNameIsNotNull() {
            addCriterion("pump_name is not null");
            return (Criteria) this;
        }

        public Criteria andPumpNameEqualTo(String value) {
            addCriterion("pump_name =", value, "pumpName");
            return (Criteria) this;
        }

        public Criteria andPumpNameNotEqualTo(String value) {
            addCriterion("pump_name <>", value, "pumpName");
            return (Criteria) this;
        }

        public Criteria andPumpNameGreaterThan(String value) {
            addCriterion("pump_name >", value, "pumpName");
            return (Criteria) this;
        }

        public Criteria andPumpNameGreaterThanOrEqualTo(String value) {
            addCriterion("pump_name >=", value, "pumpName");
            return (Criteria) this;
        }

        public Criteria andPumpNameLessThan(String value) {
            addCriterion("pump_name <", value, "pumpName");
            return (Criteria) this;
        }

        public Criteria andPumpNameLessThanOrEqualTo(String value) {
            addCriterion("pump_name <=", value, "pumpName");
            return (Criteria) this;
        }

        public Criteria andPumpNameLike(String value) {
            addCriterion("pump_name like", value, "pumpName");
            return (Criteria) this;
        }

        public Criteria andPumpNameNotLike(String value) {
            addCriterion("pump_name not like", value, "pumpName");
            return (Criteria) this;
        }

        public Criteria andPumpNameIn(List<String> values) {
            addCriterion("pump_name in", values, "pumpName");
            return (Criteria) this;
        }

        public Criteria andPumpNameNotIn(List<String> values) {
            addCriterion("pump_name not in", values, "pumpName");
            return (Criteria) this;
        }

        public Criteria andPumpNameBetween(String value1, String value2) {
            addCriterion("pump_name between", value1, value2, "pumpName");
            return (Criteria) this;
        }

        public Criteria andPumpNameNotBetween(String value1, String value2) {
            addCriterion("pump_name not between", value1, value2, "pumpName");
            return (Criteria) this;
        }

        public Criteria andPumpModelIsNull() {
            addCriterion("pump_model is null");
            return (Criteria) this;
        }

        public Criteria andPumpModelIsNotNull() {
            addCriterion("pump_model is not null");
            return (Criteria) this;
        }

        public Criteria andPumpModelEqualTo(String value) {
            addCriterion("pump_model =", value, "pumpModel");
            return (Criteria) this;
        }

        public Criteria andPumpModelNotEqualTo(String value) {
            addCriterion("pump_model <>", value, "pumpModel");
            return (Criteria) this;
        }

        public Criteria andPumpModelGreaterThan(String value) {
            addCriterion("pump_model >", value, "pumpModel");
            return (Criteria) this;
        }

        public Criteria andPumpModelGreaterThanOrEqualTo(String value) {
            addCriterion("pump_model >=", value, "pumpModel");
            return (Criteria) this;
        }

        public Criteria andPumpModelLessThan(String value) {
            addCriterion("pump_model <", value, "pumpModel");
            return (Criteria) this;
        }

        public Criteria andPumpModelLessThanOrEqualTo(String value) {
            addCriterion("pump_model <=", value, "pumpModel");
            return (Criteria) this;
        }

        public Criteria andPumpModelLike(String value) {
            addCriterion("pump_model like", value, "pumpModel");
            return (Criteria) this;
        }

        public Criteria andPumpModelNotLike(String value) {
            addCriterion("pump_model not like", value, "pumpModel");
            return (Criteria) this;
        }

        public Criteria andPumpModelIn(List<String> values) {
            addCriterion("pump_model in", values, "pumpModel");
            return (Criteria) this;
        }

        public Criteria andPumpModelNotIn(List<String> values) {
            addCriterion("pump_model not in", values, "pumpModel");
            return (Criteria) this;
        }

        public Criteria andPumpModelBetween(String value1, String value2) {
            addCriterion("pump_model between", value1, value2, "pumpModel");
            return (Criteria) this;
        }

        public Criteria andPumpModelNotBetween(String value1, String value2) {
            addCriterion("pump_model not between", value1, value2, "pumpModel");
            return (Criteria) this;
        }

        public Criteria andPumpCategoryIsNull() {
            addCriterion("pump_category is null");
            return (Criteria) this;
        }

        public Criteria andPumpCategoryIsNotNull() {
            addCriterion("pump_category is not null");
            return (Criteria) this;
        }

        public Criteria andPumpCategoryEqualTo(String value) {
            addCriterion("pump_category =", value, "pumpCategory");
            return (Criteria) this;
        }

        public Criteria andPumpCategoryNotEqualTo(String value) {
            addCriterion("pump_category <>", value, "pumpCategory");
            return (Criteria) this;
        }

        public Criteria andPumpCategoryGreaterThan(String value) {
            addCriterion("pump_category >", value, "pumpCategory");
            return (Criteria) this;
        }

        public Criteria andPumpCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("pump_category >=", value, "pumpCategory");
            return (Criteria) this;
        }

        public Criteria andPumpCategoryLessThan(String value) {
            addCriterion("pump_category <", value, "pumpCategory");
            return (Criteria) this;
        }

        public Criteria andPumpCategoryLessThanOrEqualTo(String value) {
            addCriterion("pump_category <=", value, "pumpCategory");
            return (Criteria) this;
        }

        public Criteria andPumpCategoryLike(String value) {
            addCriterion("pump_category like", value, "pumpCategory");
            return (Criteria) this;
        }

        public Criteria andPumpCategoryNotLike(String value) {
            addCriterion("pump_category not like", value, "pumpCategory");
            return (Criteria) this;
        }

        public Criteria andPumpCategoryIn(List<String> values) {
            addCriterion("pump_category in", values, "pumpCategory");
            return (Criteria) this;
        }

        public Criteria andPumpCategoryNotIn(List<String> values) {
            addCriterion("pump_category not in", values, "pumpCategory");
            return (Criteria) this;
        }

        public Criteria andPumpCategoryBetween(String value1, String value2) {
            addCriterion("pump_category between", value1, value2, "pumpCategory");
            return (Criteria) this;
        }

        public Criteria andPumpCategoryNotBetween(String value1, String value2) {
            addCriterion("pump_category not between", value1, value2, "pumpCategory");
            return (Criteria) this;
        }

        public Criteria andSpeedIsNull() {
            addCriterion("speed is null");
            return (Criteria) this;
        }

        public Criteria andSpeedIsNotNull() {
            addCriterion("speed is not null");
            return (Criteria) this;
        }

        public Criteria andSpeedEqualTo(Float value) {
            addCriterion("speed =", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotEqualTo(Float value) {
            addCriterion("speed <>", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedGreaterThan(Float value) {
            addCriterion("speed >", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedGreaterThanOrEqualTo(Float value) {
            addCriterion("speed >=", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedLessThan(Float value) {
            addCriterion("speed <", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedLessThanOrEqualTo(Float value) {
            addCriterion("speed <=", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedIn(List<Float> values) {
            addCriterion("speed in", values, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotIn(List<Float> values) {
            addCriterion("speed not in", values, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedBetween(Float value1, Float value2) {
            addCriterion("speed between", value1, value2, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotBetween(Float value1, Float value2) {
            addCriterion("speed not between", value1, value2, "speed");
            return (Criteria) this;
        }

        public Criteria andXMaxIsNull() {
            addCriterion("x_max is null");
            return (Criteria) this;
        }

        public Criteria andXMaxIsNotNull() {
            addCriterion("x_max is not null");
            return (Criteria) this;
        }

        public Criteria andXMaxEqualTo(Float value) {
            addCriterion("x_max =", value, "xMax");
            return (Criteria) this;
        }

        public Criteria andXMaxNotEqualTo(Float value) {
            addCriterion("x_max <>", value, "xMax");
            return (Criteria) this;
        }

        public Criteria andXMaxGreaterThan(Float value) {
            addCriterion("x_max >", value, "xMax");
            return (Criteria) this;
        }

        public Criteria andXMaxGreaterThanOrEqualTo(Float value) {
            addCriterion("x_max >=", value, "xMax");
            return (Criteria) this;
        }

        public Criteria andXMaxLessThan(Float value) {
            addCriterion("x_max <", value, "xMax");
            return (Criteria) this;
        }

        public Criteria andXMaxLessThanOrEqualTo(Float value) {
            addCriterion("x_max <=", value, "xMax");
            return (Criteria) this;
        }

        public Criteria andXMaxIn(List<Float> values) {
            addCriterion("x_max in", values, "xMax");
            return (Criteria) this;
        }

        public Criteria andXMaxNotIn(List<Float> values) {
            addCriterion("x_max not in", values, "xMax");
            return (Criteria) this;
        }

        public Criteria andXMaxBetween(Float value1, Float value2) {
            addCriterion("x_max between", value1, value2, "xMax");
            return (Criteria) this;
        }

        public Criteria andXMaxNotBetween(Float value1, Float value2) {
            addCriterion("x_max not between", value1, value2, "xMax");
            return (Criteria) this;
        }

        public Criteria andYMaxIsNull() {
            addCriterion("y_max is null");
            return (Criteria) this;
        }

        public Criteria andYMaxIsNotNull() {
            addCriterion("y_max is not null");
            return (Criteria) this;
        }

        public Criteria andYMaxEqualTo(Float value) {
            addCriterion("y_max =", value, "yMax");
            return (Criteria) this;
        }

        public Criteria andYMaxNotEqualTo(Float value) {
            addCriterion("y_max <>", value, "yMax");
            return (Criteria) this;
        }

        public Criteria andYMaxGreaterThan(Float value) {
            addCriterion("y_max >", value, "yMax");
            return (Criteria) this;
        }

        public Criteria andYMaxGreaterThanOrEqualTo(Float value) {
            addCriterion("y_max >=", value, "yMax");
            return (Criteria) this;
        }

        public Criteria andYMaxLessThan(Float value) {
            addCriterion("y_max <", value, "yMax");
            return (Criteria) this;
        }

        public Criteria andYMaxLessThanOrEqualTo(Float value) {
            addCriterion("y_max <=", value, "yMax");
            return (Criteria) this;
        }

        public Criteria andYMaxIn(List<Float> values) {
            addCriterion("y_max in", values, "yMax");
            return (Criteria) this;
        }

        public Criteria andYMaxNotIn(List<Float> values) {
            addCriterion("y_max not in", values, "yMax");
            return (Criteria) this;
        }

        public Criteria andYMaxBetween(Float value1, Float value2) {
            addCriterion("y_max between", value1, value2, "yMax");
            return (Criteria) this;
        }

        public Criteria andYMaxNotBetween(Float value1, Float value2) {
            addCriterion("y_max not between", value1, value2, "yMax");
            return (Criteria) this;
        }

        public Criteria andBepXmaxIsNull() {
            addCriterion("bep_xmax is null");
            return (Criteria) this;
        }

        public Criteria andBepXmaxIsNotNull() {
            addCriterion("bep_xmax is not null");
            return (Criteria) this;
        }

        public Criteria andBepXmaxEqualTo(Float value) {
            addCriterion("bep_xmax =", value, "bepXmax");
            return (Criteria) this;
        }

        public Criteria andBepXmaxNotEqualTo(Float value) {
            addCriterion("bep_xmax <>", value, "bepXmax");
            return (Criteria) this;
        }

        public Criteria andBepXmaxGreaterThan(Float value) {
            addCriterion("bep_xmax >", value, "bepXmax");
            return (Criteria) this;
        }

        public Criteria andBepXmaxGreaterThanOrEqualTo(Float value) {
            addCriterion("bep_xmax >=", value, "bepXmax");
            return (Criteria) this;
        }

        public Criteria andBepXmaxLessThan(Float value) {
            addCriterion("bep_xmax <", value, "bepXmax");
            return (Criteria) this;
        }

        public Criteria andBepXmaxLessThanOrEqualTo(Float value) {
            addCriterion("bep_xmax <=", value, "bepXmax");
            return (Criteria) this;
        }

        public Criteria andBepXmaxIn(List<Float> values) {
            addCriterion("bep_xmax in", values, "bepXmax");
            return (Criteria) this;
        }

        public Criteria andBepXmaxNotIn(List<Float> values) {
            addCriterion("bep_xmax not in", values, "bepXmax");
            return (Criteria) this;
        }

        public Criteria andBepXmaxBetween(Float value1, Float value2) {
            addCriterion("bep_xmax between", value1, value2, "bepXmax");
            return (Criteria) this;
        }

        public Criteria andBepXmaxNotBetween(Float value1, Float value2) {
            addCriterion("bep_xmax not between", value1, value2, "bepXmax");
            return (Criteria) this;
        }

        public Criteria andBepYmaxIsNull() {
            addCriterion("bep_ymax is null");
            return (Criteria) this;
        }

        public Criteria andBepYmaxIsNotNull() {
            addCriterion("bep_ymax is not null");
            return (Criteria) this;
        }

        public Criteria andBepYmaxEqualTo(Float value) {
            addCriterion("bep_ymax =", value, "bepYmax");
            return (Criteria) this;
        }

        public Criteria andBepYmaxNotEqualTo(Float value) {
            addCriterion("bep_ymax <>", value, "bepYmax");
            return (Criteria) this;
        }

        public Criteria andBepYmaxGreaterThan(Float value) {
            addCriterion("bep_ymax >", value, "bepYmax");
            return (Criteria) this;
        }

        public Criteria andBepYmaxGreaterThanOrEqualTo(Float value) {
            addCriterion("bep_ymax >=", value, "bepYmax");
            return (Criteria) this;
        }

        public Criteria andBepYmaxLessThan(Float value) {
            addCriterion("bep_ymax <", value, "bepYmax");
            return (Criteria) this;
        }

        public Criteria andBepYmaxLessThanOrEqualTo(Float value) {
            addCriterion("bep_ymax <=", value, "bepYmax");
            return (Criteria) this;
        }

        public Criteria andBepYmaxIn(List<Float> values) {
            addCriterion("bep_ymax in", values, "bepYmax");
            return (Criteria) this;
        }

        public Criteria andBepYmaxNotIn(List<Float> values) {
            addCriterion("bep_ymax not in", values, "bepYmax");
            return (Criteria) this;
        }

        public Criteria andBepYmaxBetween(Float value1, Float value2) {
            addCriterion("bep_ymax between", value1, value2, "bepYmax");
            return (Criteria) this;
        }

        public Criteria andBepYmaxNotBetween(Float value1, Float value2) {
            addCriterion("bep_ymax not between", value1, value2, "bepYmax");
            return (Criteria) this;
        }

        public Criteria andBepXminIsNull() {
            addCriterion("bep_xmin is null");
            return (Criteria) this;
        }

        public Criteria andBepXminIsNotNull() {
            addCriterion("bep_xmin is not null");
            return (Criteria) this;
        }

        public Criteria andBepXminEqualTo(Float value) {
            addCriterion("bep_xmin =", value, "bepXmin");
            return (Criteria) this;
        }

        public Criteria andBepXminNotEqualTo(Float value) {
            addCriterion("bep_xmin <>", value, "bepXmin");
            return (Criteria) this;
        }

        public Criteria andBepXminGreaterThan(Float value) {
            addCriterion("bep_xmin >", value, "bepXmin");
            return (Criteria) this;
        }

        public Criteria andBepXminGreaterThanOrEqualTo(Float value) {
            addCriterion("bep_xmin >=", value, "bepXmin");
            return (Criteria) this;
        }

        public Criteria andBepXminLessThan(Float value) {
            addCriterion("bep_xmin <", value, "bepXmin");
            return (Criteria) this;
        }

        public Criteria andBepXminLessThanOrEqualTo(Float value) {
            addCriterion("bep_xmin <=", value, "bepXmin");
            return (Criteria) this;
        }

        public Criteria andBepXminIn(List<Float> values) {
            addCriterion("bep_xmin in", values, "bepXmin");
            return (Criteria) this;
        }

        public Criteria andBepXminNotIn(List<Float> values) {
            addCriterion("bep_xmin not in", values, "bepXmin");
            return (Criteria) this;
        }

        public Criteria andBepXminBetween(Float value1, Float value2) {
            addCriterion("bep_xmin between", value1, value2, "bepXmin");
            return (Criteria) this;
        }

        public Criteria andBepXminNotBetween(Float value1, Float value2) {
            addCriterion("bep_xmin not between", value1, value2, "bepXmin");
            return (Criteria) this;
        }

        public Criteria andBepYminIsNull() {
            addCriterion("bep_ymin is null");
            return (Criteria) this;
        }

        public Criteria andBepYminIsNotNull() {
            addCriterion("bep_ymin is not null");
            return (Criteria) this;
        }

        public Criteria andBepYminEqualTo(Float value) {
            addCriterion("bep_ymin =", value, "bepYmin");
            return (Criteria) this;
        }

        public Criteria andBepYminNotEqualTo(Float value) {
            addCriterion("bep_ymin <>", value, "bepYmin");
            return (Criteria) this;
        }

        public Criteria andBepYminGreaterThan(Float value) {
            addCriterion("bep_ymin >", value, "bepYmin");
            return (Criteria) this;
        }

        public Criteria andBepYminGreaterThanOrEqualTo(Float value) {
            addCriterion("bep_ymin >=", value, "bepYmin");
            return (Criteria) this;
        }

        public Criteria andBepYminLessThan(Float value) {
            addCriterion("bep_ymin <", value, "bepYmin");
            return (Criteria) this;
        }

        public Criteria andBepYminLessThanOrEqualTo(Float value) {
            addCriterion("bep_ymin <=", value, "bepYmin");
            return (Criteria) this;
        }

        public Criteria andBepYminIn(List<Float> values) {
            addCriterion("bep_ymin in", values, "bepYmin");
            return (Criteria) this;
        }

        public Criteria andBepYminNotIn(List<Float> values) {
            addCriterion("bep_ymin not in", values, "bepYmin");
            return (Criteria) this;
        }

        public Criteria andBepYminBetween(Float value1, Float value2) {
            addCriterion("bep_ymin between", value1, value2, "bepYmin");
            return (Criteria) this;
        }

        public Criteria andBepYminNotBetween(Float value1, Float value2) {
            addCriterion("bep_ymin not between", value1, value2, "bepYmin");
            return (Criteria) this;
        }

        public Criteria andQminIsNull() {
            addCriterion("qmin is null");
            return (Criteria) this;
        }

        public Criteria andQminIsNotNull() {
            addCriterion("qmin is not null");
            return (Criteria) this;
        }

        public Criteria andQminEqualTo(Float value) {
            addCriterion("qmin =", value, "qmin");
            return (Criteria) this;
        }

        public Criteria andQminNotEqualTo(Float value) {
            addCriterion("qmin <>", value, "qmin");
            return (Criteria) this;
        }

        public Criteria andQminGreaterThan(Float value) {
            addCriterion("qmin >", value, "qmin");
            return (Criteria) this;
        }

        public Criteria andQminGreaterThanOrEqualTo(Float value) {
            addCriterion("qmin >=", value, "qmin");
            return (Criteria) this;
        }

        public Criteria andQminLessThan(Float value) {
            addCriterion("qmin <", value, "qmin");
            return (Criteria) this;
        }

        public Criteria andQminLessThanOrEqualTo(Float value) {
            addCriterion("qmin <=", value, "qmin");
            return (Criteria) this;
        }

        public Criteria andQminIn(List<Float> values) {
            addCriterion("qmin in", values, "qmin");
            return (Criteria) this;
        }

        public Criteria andQminNotIn(List<Float> values) {
            addCriterion("qmin not in", values, "qmin");
            return (Criteria) this;
        }

        public Criteria andQminBetween(Float value1, Float value2) {
            addCriterion("qmin between", value1, value2, "qmin");
            return (Criteria) this;
        }

        public Criteria andQminNotBetween(Float value1, Float value2) {
            addCriterion("qmin not between", value1, value2, "qmin");
            return (Criteria) this;
        }

        public Criteria andYStartIsNull() {
            addCriterion("y_start is null");
            return (Criteria) this;
        }

        public Criteria andYStartIsNotNull() {
            addCriterion("y_start is not null");
            return (Criteria) this;
        }

        public Criteria andYStartEqualTo(Float value) {
            addCriterion("y_start =", value, "yStart");
            return (Criteria) this;
        }

        public Criteria andYStartNotEqualTo(Float value) {
            addCriterion("y_start <>", value, "yStart");
            return (Criteria) this;
        }

        public Criteria andYStartGreaterThan(Float value) {
            addCriterion("y_start >", value, "yStart");
            return (Criteria) this;
        }

        public Criteria andYStartGreaterThanOrEqualTo(Float value) {
            addCriterion("y_start >=", value, "yStart");
            return (Criteria) this;
        }

        public Criteria andYStartLessThan(Float value) {
            addCriterion("y_start <", value, "yStart");
            return (Criteria) this;
        }

        public Criteria andYStartLessThanOrEqualTo(Float value) {
            addCriterion("y_start <=", value, "yStart");
            return (Criteria) this;
        }

        public Criteria andYStartIn(List<Float> values) {
            addCriterion("y_start in", values, "yStart");
            return (Criteria) this;
        }

        public Criteria andYStartNotIn(List<Float> values) {
            addCriterion("y_start not in", values, "yStart");
            return (Criteria) this;
        }

        public Criteria andYStartBetween(Float value1, Float value2) {
            addCriterion("y_start between", value1, value2, "yStart");
            return (Criteria) this;
        }

        public Criteria andYStartNotBetween(Float value1, Float value2) {
            addCriterion("y_start not between", value1, value2, "yStart");
            return (Criteria) this;
        }

        public Criteria andQMinMaxIsNull() {
            addCriterion("q_min_max is null");
            return (Criteria) this;
        }

        public Criteria andQMinMaxIsNotNull() {
            addCriterion("q_min_max is not null");
            return (Criteria) this;
        }

        public Criteria andQMinMaxEqualTo(Float value) {
            addCriterion("q_min_max =", value, "qMinMax");
            return (Criteria) this;
        }

        public Criteria andQMinMaxNotEqualTo(Float value) {
            addCriterion("q_min_max <>", value, "qMinMax");
            return (Criteria) this;
        }

        public Criteria andQMinMaxGreaterThan(Float value) {
            addCriterion("q_min_max >", value, "qMinMax");
            return (Criteria) this;
        }

        public Criteria andQMinMaxGreaterThanOrEqualTo(Float value) {
            addCriterion("q_min_max >=", value, "qMinMax");
            return (Criteria) this;
        }

        public Criteria andQMinMaxLessThan(Float value) {
            addCriterion("q_min_max <", value, "qMinMax");
            return (Criteria) this;
        }

        public Criteria andQMinMaxLessThanOrEqualTo(Float value) {
            addCriterion("q_min_max <=", value, "qMinMax");
            return (Criteria) this;
        }

        public Criteria andQMinMaxIn(List<Float> values) {
            addCriterion("q_min_max in", values, "qMinMax");
            return (Criteria) this;
        }

        public Criteria andQMinMaxNotIn(List<Float> values) {
            addCriterion("q_min_max not in", values, "qMinMax");
            return (Criteria) this;
        }

        public Criteria andQMinMaxBetween(Float value1, Float value2) {
            addCriterion("q_min_max between", value1, value2, "qMinMax");
            return (Criteria) this;
        }

        public Criteria andQMinMaxNotBetween(Float value1, Float value2) {
            addCriterion("q_min_max not between", value1, value2, "qMinMax");
            return (Criteria) this;
        }

        public Criteria andQMaxMaxIsNull() {
            addCriterion("q_max_max is null");
            return (Criteria) this;
        }

        public Criteria andQMaxMaxIsNotNull() {
            addCriterion("q_max_max is not null");
            return (Criteria) this;
        }

        public Criteria andQMaxMaxEqualTo(Float value) {
            addCriterion("q_max_max =", value, "qMaxMax");
            return (Criteria) this;
        }

        public Criteria andQMaxMaxNotEqualTo(Float value) {
            addCriterion("q_max_max <>", value, "qMaxMax");
            return (Criteria) this;
        }

        public Criteria andQMaxMaxGreaterThan(Float value) {
            addCriterion("q_max_max >", value, "qMaxMax");
            return (Criteria) this;
        }

        public Criteria andQMaxMaxGreaterThanOrEqualTo(Float value) {
            addCriterion("q_max_max >=", value, "qMaxMax");
            return (Criteria) this;
        }

        public Criteria andQMaxMaxLessThan(Float value) {
            addCriterion("q_max_max <", value, "qMaxMax");
            return (Criteria) this;
        }

        public Criteria andQMaxMaxLessThanOrEqualTo(Float value) {
            addCriterion("q_max_max <=", value, "qMaxMax");
            return (Criteria) this;
        }

        public Criteria andQMaxMaxIn(List<Float> values) {
            addCriterion("q_max_max in", values, "qMaxMax");
            return (Criteria) this;
        }

        public Criteria andQMaxMaxNotIn(List<Float> values) {
            addCriterion("q_max_max not in", values, "qMaxMax");
            return (Criteria) this;
        }

        public Criteria andQMaxMaxBetween(Float value1, Float value2) {
            addCriterion("q_max_max between", value1, value2, "qMaxMax");
            return (Criteria) this;
        }

        public Criteria andQMaxMaxNotBetween(Float value1, Float value2) {
            addCriterion("q_max_max not between", value1, value2, "qMaxMax");
            return (Criteria) this;
        }

        public Criteria andShutdownMaxIsNull() {
            addCriterion("shutdown_max is null");
            return (Criteria) this;
        }

        public Criteria andShutdownMaxIsNotNull() {
            addCriterion("shutdown_max is not null");
            return (Criteria) this;
        }

        public Criteria andShutdownMaxEqualTo(Float value) {
            addCriterion("shutdown_max =", value, "shutdownMax");
            return (Criteria) this;
        }

        public Criteria andShutdownMaxNotEqualTo(Float value) {
            addCriterion("shutdown_max <>", value, "shutdownMax");
            return (Criteria) this;
        }

        public Criteria andShutdownMaxGreaterThan(Float value) {
            addCriterion("shutdown_max >", value, "shutdownMax");
            return (Criteria) this;
        }

        public Criteria andShutdownMaxGreaterThanOrEqualTo(Float value) {
            addCriterion("shutdown_max >=", value, "shutdownMax");
            return (Criteria) this;
        }

        public Criteria andShutdownMaxLessThan(Float value) {
            addCriterion("shutdown_max <", value, "shutdownMax");
            return (Criteria) this;
        }

        public Criteria andShutdownMaxLessThanOrEqualTo(Float value) {
            addCriterion("shutdown_max <=", value, "shutdownMax");
            return (Criteria) this;
        }

        public Criteria andShutdownMaxIn(List<Float> values) {
            addCriterion("shutdown_max in", values, "shutdownMax");
            return (Criteria) this;
        }

        public Criteria andShutdownMaxNotIn(List<Float> values) {
            addCriterion("shutdown_max not in", values, "shutdownMax");
            return (Criteria) this;
        }

        public Criteria andShutdownMaxBetween(Float value1, Float value2) {
            addCriterion("shutdown_max between", value1, value2, "shutdownMax");
            return (Criteria) this;
        }

        public Criteria andShutdownMaxNotBetween(Float value1, Float value2) {
            addCriterion("shutdown_max not between", value1, value2, "shutdownMax");
            return (Criteria) this;
        }

        public Criteria andShutdownMinIsNull() {
            addCriterion("shutdown_min is null");
            return (Criteria) this;
        }

        public Criteria andShutdownMinIsNotNull() {
            addCriterion("shutdown_min is not null");
            return (Criteria) this;
        }

        public Criteria andShutdownMinEqualTo(Float value) {
            addCriterion("shutdown_min =", value, "shutdownMin");
            return (Criteria) this;
        }

        public Criteria andShutdownMinNotEqualTo(Float value) {
            addCriterion("shutdown_min <>", value, "shutdownMin");
            return (Criteria) this;
        }

        public Criteria andShutdownMinGreaterThan(Float value) {
            addCriterion("shutdown_min >", value, "shutdownMin");
            return (Criteria) this;
        }

        public Criteria andShutdownMinGreaterThanOrEqualTo(Float value) {
            addCriterion("shutdown_min >=", value, "shutdownMin");
            return (Criteria) this;
        }

        public Criteria andShutdownMinLessThan(Float value) {
            addCriterion("shutdown_min <", value, "shutdownMin");
            return (Criteria) this;
        }

        public Criteria andShutdownMinLessThanOrEqualTo(Float value) {
            addCriterion("shutdown_min <=", value, "shutdownMin");
            return (Criteria) this;
        }

        public Criteria andShutdownMinIn(List<Float> values) {
            addCriterion("shutdown_min in", values, "shutdownMin");
            return (Criteria) this;
        }

        public Criteria andShutdownMinNotIn(List<Float> values) {
            addCriterion("shutdown_min not in", values, "shutdownMin");
            return (Criteria) this;
        }

        public Criteria andShutdownMinBetween(Float value1, Float value2) {
            addCriterion("shutdown_min between", value1, value2, "shutdownMin");
            return (Criteria) this;
        }

        public Criteria andShutdownMinNotBetween(Float value1, Float value2) {
            addCriterion("shutdown_min not between", value1, value2, "shutdownMin");
            return (Criteria) this;
        }

        public Criteria andPhiIsNull() {
            addCriterion("phi is null");
            return (Criteria) this;
        }

        public Criteria andPhiIsNotNull() {
            addCriterion("phi is not null");
            return (Criteria) this;
        }

        public Criteria andPhiEqualTo(Float value) {
            addCriterion("phi =", value, "phi");
            return (Criteria) this;
        }

        public Criteria andPhiNotEqualTo(Float value) {
            addCriterion("phi <>", value, "phi");
            return (Criteria) this;
        }

        public Criteria andPhiGreaterThan(Float value) {
            addCriterion("phi >", value, "phi");
            return (Criteria) this;
        }

        public Criteria andPhiGreaterThanOrEqualTo(Float value) {
            addCriterion("phi >=", value, "phi");
            return (Criteria) this;
        }

        public Criteria andPhiLessThan(Float value) {
            addCriterion("phi <", value, "phi");
            return (Criteria) this;
        }

        public Criteria andPhiLessThanOrEqualTo(Float value) {
            addCriterion("phi <=", value, "phi");
            return (Criteria) this;
        }

        public Criteria andPhiIn(List<Float> values) {
            addCriterion("phi in", values, "phi");
            return (Criteria) this;
        }

        public Criteria andPhiNotIn(List<Float> values) {
            addCriterion("phi not in", values, "phi");
            return (Criteria) this;
        }

        public Criteria andPhiBetween(Float value1, Float value2) {
            addCriterion("phi between", value1, value2, "phi");
            return (Criteria) this;
        }

        public Criteria andPhiNotBetween(Float value1, Float value2) {
            addCriterion("phi not between", value1, value2, "phi");
            return (Criteria) this;
        }

        public Criteria andPhiMaxIsNull() {
            addCriterion("phi_max is null");
            return (Criteria) this;
        }

        public Criteria andPhiMaxIsNotNull() {
            addCriterion("phi_max is not null");
            return (Criteria) this;
        }

        public Criteria andPhiMaxEqualTo(Float value) {
            addCriterion("phi_max =", value, "phiMax");
            return (Criteria) this;
        }

        public Criteria andPhiMaxNotEqualTo(Float value) {
            addCriterion("phi_max <>", value, "phiMax");
            return (Criteria) this;
        }

        public Criteria andPhiMaxGreaterThan(Float value) {
            addCriterion("phi_max >", value, "phiMax");
            return (Criteria) this;
        }

        public Criteria andPhiMaxGreaterThanOrEqualTo(Float value) {
            addCriterion("phi_max >=", value, "phiMax");
            return (Criteria) this;
        }

        public Criteria andPhiMaxLessThan(Float value) {
            addCriterion("phi_max <", value, "phiMax");
            return (Criteria) this;
        }

        public Criteria andPhiMaxLessThanOrEqualTo(Float value) {
            addCriterion("phi_max <=", value, "phiMax");
            return (Criteria) this;
        }

        public Criteria andPhiMaxIn(List<Float> values) {
            addCriterion("phi_max in", values, "phiMax");
            return (Criteria) this;
        }

        public Criteria andPhiMaxNotIn(List<Float> values) {
            addCriterion("phi_max not in", values, "phiMax");
            return (Criteria) this;
        }

        public Criteria andPhiMaxBetween(Float value1, Float value2) {
            addCriterion("phi_max between", value1, value2, "phiMax");
            return (Criteria) this;
        }

        public Criteria andPhiMaxNotBetween(Float value1, Float value2) {
            addCriterion("phi_max not between", value1, value2, "phiMax");
            return (Criteria) this;
        }

        public Criteria andPhiMinIsNull() {
            addCriterion("phi_min is null");
            return (Criteria) this;
        }

        public Criteria andPhiMinIsNotNull() {
            addCriterion("phi_min is not null");
            return (Criteria) this;
        }

        public Criteria andPhiMinEqualTo(Float value) {
            addCriterion("phi_min =", value, "phiMin");
            return (Criteria) this;
        }

        public Criteria andPhiMinNotEqualTo(Float value) {
            addCriterion("phi_min <>", value, "phiMin");
            return (Criteria) this;
        }

        public Criteria andPhiMinGreaterThan(Float value) {
            addCriterion("phi_min >", value, "phiMin");
            return (Criteria) this;
        }

        public Criteria andPhiMinGreaterThanOrEqualTo(Float value) {
            addCriterion("phi_min >=", value, "phiMin");
            return (Criteria) this;
        }

        public Criteria andPhiMinLessThan(Float value) {
            addCriterion("phi_min <", value, "phiMin");
            return (Criteria) this;
        }

        public Criteria andPhiMinLessThanOrEqualTo(Float value) {
            addCriterion("phi_min <=", value, "phiMin");
            return (Criteria) this;
        }

        public Criteria andPhiMinIn(List<Float> values) {
            addCriterion("phi_min in", values, "phiMin");
            return (Criteria) this;
        }

        public Criteria andPhiMinNotIn(List<Float> values) {
            addCriterion("phi_min not in", values, "phiMin");
            return (Criteria) this;
        }

        public Criteria andPhiMinBetween(Float value1, Float value2) {
            addCriterion("phi_min between", value1, value2, "phiMin");
            return (Criteria) this;
        }

        public Criteria andPhiMinNotBetween(Float value1, Float value2) {
            addCriterion("phi_min not between", value1, value2, "phiMin");
            return (Criteria) this;
        }

        public Criteria andMinPointIsNull() {
            addCriterion("min_point is null");
            return (Criteria) this;
        }

        public Criteria andMinPointIsNotNull() {
            addCriterion("min_point is not null");
            return (Criteria) this;
        }

        public Criteria andMinPointEqualTo(Float value) {
            addCriterion("min_point =", value, "minPoint");
            return (Criteria) this;
        }

        public Criteria andMinPointNotEqualTo(Float value) {
            addCriterion("min_point <>", value, "minPoint");
            return (Criteria) this;
        }

        public Criteria andMinPointGreaterThan(Float value) {
            addCriterion("min_point >", value, "minPoint");
            return (Criteria) this;
        }

        public Criteria andMinPointGreaterThanOrEqualTo(Float value) {
            addCriterion("min_point >=", value, "minPoint");
            return (Criteria) this;
        }

        public Criteria andMinPointLessThan(Float value) {
            addCriterion("min_point <", value, "minPoint");
            return (Criteria) this;
        }

        public Criteria andMinPointLessThanOrEqualTo(Float value) {
            addCriterion("min_point <=", value, "minPoint");
            return (Criteria) this;
        }

        public Criteria andMinPointIn(List<Float> values) {
            addCriterion("min_point in", values, "minPoint");
            return (Criteria) this;
        }

        public Criteria andMinPointNotIn(List<Float> values) {
            addCriterion("min_point not in", values, "minPoint");
            return (Criteria) this;
        }

        public Criteria andMinPointBetween(Float value1, Float value2) {
            addCriterion("min_point between", value1, value2, "minPoint");
            return (Criteria) this;
        }

        public Criteria andMinPointNotBetween(Float value1, Float value2) {
            addCriterion("min_point not between", value1, value2, "minPoint");
            return (Criteria) this;
        }

        public Criteria andStaPointIsNull() {
            addCriterion("sta_point is null");
            return (Criteria) this;
        }

        public Criteria andStaPointIsNotNull() {
            addCriterion("sta_point is not null");
            return (Criteria) this;
        }

        public Criteria andStaPointEqualTo(Float value) {
            addCriterion("sta_point =", value, "staPoint");
            return (Criteria) this;
        }

        public Criteria andStaPointNotEqualTo(Float value) {
            addCriterion("sta_point <>", value, "staPoint");
            return (Criteria) this;
        }

        public Criteria andStaPointGreaterThan(Float value) {
            addCriterion("sta_point >", value, "staPoint");
            return (Criteria) this;
        }

        public Criteria andStaPointGreaterThanOrEqualTo(Float value) {
            addCriterion("sta_point >=", value, "staPoint");
            return (Criteria) this;
        }

        public Criteria andStaPointLessThan(Float value) {
            addCriterion("sta_point <", value, "staPoint");
            return (Criteria) this;
        }

        public Criteria andStaPointLessThanOrEqualTo(Float value) {
            addCriterion("sta_point <=", value, "staPoint");
            return (Criteria) this;
        }

        public Criteria andStaPointIn(List<Float> values) {
            addCriterion("sta_point in", values, "staPoint");
            return (Criteria) this;
        }

        public Criteria andStaPointNotIn(List<Float> values) {
            addCriterion("sta_point not in", values, "staPoint");
            return (Criteria) this;
        }

        public Criteria andStaPointBetween(Float value1, Float value2) {
            addCriterion("sta_point between", value1, value2, "staPoint");
            return (Criteria) this;
        }

        public Criteria andStaPointNotBetween(Float value1, Float value2) {
            addCriterion("sta_point not between", value1, value2, "staPoint");
            return (Criteria) this;
        }

        public Criteria andMaxPointIsNull() {
            addCriterion("max_point is null");
            return (Criteria) this;
        }

        public Criteria andMaxPointIsNotNull() {
            addCriterion("max_point is not null");
            return (Criteria) this;
        }

        public Criteria andMaxPointEqualTo(Float value) {
            addCriterion("max_point =", value, "maxPoint");
            return (Criteria) this;
        }

        public Criteria andMaxPointNotEqualTo(Float value) {
            addCriterion("max_point <>", value, "maxPoint");
            return (Criteria) this;
        }

        public Criteria andMaxPointGreaterThan(Float value) {
            addCriterion("max_point >", value, "maxPoint");
            return (Criteria) this;
        }

        public Criteria andMaxPointGreaterThanOrEqualTo(Float value) {
            addCriterion("max_point >=", value, "maxPoint");
            return (Criteria) this;
        }

        public Criteria andMaxPointLessThan(Float value) {
            addCriterion("max_point <", value, "maxPoint");
            return (Criteria) this;
        }

        public Criteria andMaxPointLessThanOrEqualTo(Float value) {
            addCriterion("max_point <=", value, "maxPoint");
            return (Criteria) this;
        }

        public Criteria andMaxPointIn(List<Float> values) {
            addCriterion("max_point in", values, "maxPoint");
            return (Criteria) this;
        }

        public Criteria andMaxPointNotIn(List<Float> values) {
            addCriterion("max_point not in", values, "maxPoint");
            return (Criteria) this;
        }

        public Criteria andMaxPointBetween(Float value1, Float value2) {
            addCriterion("max_point between", value1, value2, "maxPoint");
            return (Criteria) this;
        }

        public Criteria andMaxPointNotBetween(Float value1, Float value2) {
            addCriterion("max_point not between", value1, value2, "maxPoint");
            return (Criteria) this;
        }

        public Criteria andNpshrIsNull() {
            addCriterion("npshr is null");
            return (Criteria) this;
        }

        public Criteria andNpshrIsNotNull() {
            addCriterion("npshr is not null");
            return (Criteria) this;
        }

        public Criteria andNpshrEqualTo(Float value) {
            addCriterion("npshr =", value, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrNotEqualTo(Float value) {
            addCriterion("npshr <>", value, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrGreaterThan(Float value) {
            addCriterion("npshr >", value, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrGreaterThanOrEqualTo(Float value) {
            addCriterion("npshr >=", value, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrLessThan(Float value) {
            addCriterion("npshr <", value, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrLessThanOrEqualTo(Float value) {
            addCriterion("npshr <=", value, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrIn(List<Float> values) {
            addCriterion("npshr in", values, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrNotIn(List<Float> values) {
            addCriterion("npshr not in", values, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrBetween(Float value1, Float value2) {
            addCriterion("npshr between", value1, value2, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrNotBetween(Float value1, Float value2) {
            addCriterion("npshr not between", value1, value2, "npshr");
            return (Criteria) this;
        }

        public Criteria andPumpSourceIsNull() {
            addCriterion("pump_source is null");
            return (Criteria) this;
        }

        public Criteria andPumpSourceIsNotNull() {
            addCriterion("pump_source is not null");
            return (Criteria) this;
        }

        public Criteria andPumpSourceEqualTo(String value) {
            addCriterion("pump_source =", value, "pumpSource");
            return (Criteria) this;
        }

        public Criteria andPumpSourceNotEqualTo(String value) {
            addCriterion("pump_source <>", value, "pumpSource");
            return (Criteria) this;
        }

        public Criteria andPumpSourceGreaterThan(String value) {
            addCriterion("pump_source >", value, "pumpSource");
            return (Criteria) this;
        }

        public Criteria andPumpSourceGreaterThanOrEqualTo(String value) {
            addCriterion("pump_source >=", value, "pumpSource");
            return (Criteria) this;
        }

        public Criteria andPumpSourceLessThan(String value) {
            addCriterion("pump_source <", value, "pumpSource");
            return (Criteria) this;
        }

        public Criteria andPumpSourceLessThanOrEqualTo(String value) {
            addCriterion("pump_source <=", value, "pumpSource");
            return (Criteria) this;
        }

        public Criteria andPumpSourceLike(String value) {
            addCriterion("pump_source like", value, "pumpSource");
            return (Criteria) this;
        }

        public Criteria andPumpSourceNotLike(String value) {
            addCriterion("pump_source not like", value, "pumpSource");
            return (Criteria) this;
        }

        public Criteria andPumpSourceIn(List<String> values) {
            addCriterion("pump_source in", values, "pumpSource");
            return (Criteria) this;
        }

        public Criteria andPumpSourceNotIn(List<String> values) {
            addCriterion("pump_source not in", values, "pumpSource");
            return (Criteria) this;
        }

        public Criteria andPumpSourceBetween(String value1, String value2) {
            addCriterion("pump_source between", value1, value2, "pumpSource");
            return (Criteria) this;
        }

        public Criteria andPumpSourceNotBetween(String value1, String value2) {
            addCriterion("pump_source not between", value1, value2, "pumpSource");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdIsNull() {
            addCriterion("created_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdIsNotNull() {
            addCriterion("created_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdEqualTo(String value) {
            addCriterion("created_user_id =", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotEqualTo(String value) {
            addCriterion("created_user_id <>", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdGreaterThan(String value) {
            addCriterion("created_user_id >", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("created_user_id >=", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdLessThan(String value) {
            addCriterion("created_user_id <", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdLessThanOrEqualTo(String value) {
            addCriterion("created_user_id <=", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdLike(String value) {
            addCriterion("created_user_id like", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotLike(String value) {
            addCriterion("created_user_id not like", value, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdIn(List<String> values) {
            addCriterion("created_user_id in", values, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotIn(List<String> values) {
            addCriterion("created_user_id not in", values, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdBetween(String value1, String value2) {
            addCriterion("created_user_id between", value1, value2, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIdNotBetween(String value1, String value2) {
            addCriterion("created_user_id not between", value1, value2, "createdUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(LocalDateTime value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(LocalDateTime value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(LocalDateTime value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(LocalDateTime value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<LocalDateTime> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<LocalDateTime> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdIsNull() {
            addCriterion("updated_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdIsNotNull() {
            addCriterion("updated_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdEqualTo(String value) {
            addCriterion("updated_user_id =", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdNotEqualTo(String value) {
            addCriterion("updated_user_id <>", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdGreaterThan(String value) {
            addCriterion("updated_user_id >", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("updated_user_id >=", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdLessThan(String value) {
            addCriterion("updated_user_id <", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdLessThanOrEqualTo(String value) {
            addCriterion("updated_user_id <=", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdLike(String value) {
            addCriterion("updated_user_id like", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdNotLike(String value) {
            addCriterion("updated_user_id not like", value, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdIn(List<String> values) {
            addCriterion("updated_user_id in", values, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdNotIn(List<String> values) {
            addCriterion("updated_user_id not in", values, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdBetween(String value1, String value2) {
            addCriterion("updated_user_id between", value1, value2, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIdNotBetween(String value1, String value2) {
            addCriterion("updated_user_id not between", value1, value2, "updatedUserId");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("updated_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("updated_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(LocalDateTime value) {
            addCriterion("updated_time =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(LocalDateTime value) {
            addCriterion("updated_time <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(LocalDateTime value) {
            addCriterion("updated_time >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_time >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(LocalDateTime value) {
            addCriterion("updated_time <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_time <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<LocalDateTime> values) {
            addCriterion("updated_time in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<LocalDateTime> values) {
            addCriterion("updated_time not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_time between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_time not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagEqualTo(String value) {
            addCriterion("is_deleted =", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotEqualTo(String value) {
            addCriterion("is_deleted <>", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThan(String value) {
            addCriterion("is_deleted >", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThanOrEqualTo(String value) {
            addCriterion("is_deleted >=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThan(String value) {
            addCriterion("is_deleted <", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThanOrEqualTo(String value) {
            addCriterion("is_deleted <=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLike(String value) {
            addCriterion("is_deleted like", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotLike(String value) {
            addCriterion("is_deleted not like", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIn(List<String> values) {
            addCriterion("is_deleted in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotIn(List<String> values) {
            addCriterion("is_deleted not in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagBetween(String value1, String value2) {
            addCriterion("is_deleted between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotBetween(String value1, String value2) {
            addCriterion("is_deleted not between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pump_information
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 30 00:47:13 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pump_information
     *
     * @mbg.generated Thu Mar 30 00:47:13 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}