package com.t.zero.b.i.pump.db.model.auto;

import java.io.Serializable;
import java.time.LocalDateTime;

public class PumpFaLanInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pump_fa_lan_info.id
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pump_fa_lan_info.pv_code
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private String pvCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pump_fa_lan_info.flange_standard
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private String flangeStandard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pump_fa_lan_info.flang_type
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private String flangType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pump_fa_lan_info.pressure
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private String pressure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pump_fa_lan_info.seal_face
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private String sealFace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pump_fa_lan_info.dn
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private Float dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pump_fa_lan_info.dn_type
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private String dnType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pump_fa_lan_info.pump_source
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private String pumpSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pump_fa_lan_info.created_user_id
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pump_fa_lan_info.created_time
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private LocalDateTime createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pump_fa_lan_info.updated_user_id
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private String updatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pump_fa_lan_info.updated_time
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private LocalDateTime updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pump_fa_lan_info.is_deleted
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private String deletedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pump_fa_lan_info.pv_desc
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private String pvDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pump_fa_lan_info
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pump_fa_lan_info.id
     *
     * @return the value of pump_fa_lan_info.id
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pump_fa_lan_info.id
     *
     * @param id the value for pump_fa_lan_info.id
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pump_fa_lan_info.pv_code
     *
     * @return the value of pump_fa_lan_info.pv_code
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public String getPvCode() {
        return pvCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pump_fa_lan_info.pv_code
     *
     * @param pvCode the value for pump_fa_lan_info.pv_code
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public void setPvCode(String pvCode) {
        this.pvCode = pvCode == null ? null : pvCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pump_fa_lan_info.flange_standard
     *
     * @return the value of pump_fa_lan_info.flange_standard
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public String getFlangeStandard() {
        return flangeStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pump_fa_lan_info.flange_standard
     *
     * @param flangeStandard the value for pump_fa_lan_info.flange_standard
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public void setFlangeStandard(String flangeStandard) {
        this.flangeStandard = flangeStandard == null ? null : flangeStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pump_fa_lan_info.flang_type
     *
     * @return the value of pump_fa_lan_info.flang_type
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public String getFlangType() {
        return flangType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pump_fa_lan_info.flang_type
     *
     * @param flangType the value for pump_fa_lan_info.flang_type
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public void setFlangType(String flangType) {
        this.flangType = flangType == null ? null : flangType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pump_fa_lan_info.pressure
     *
     * @return the value of pump_fa_lan_info.pressure
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public String getPressure() {
        return pressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pump_fa_lan_info.pressure
     *
     * @param pressure the value for pump_fa_lan_info.pressure
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public void setPressure(String pressure) {
        this.pressure = pressure == null ? null : pressure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pump_fa_lan_info.seal_face
     *
     * @return the value of pump_fa_lan_info.seal_face
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public String getSealFace() {
        return sealFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pump_fa_lan_info.seal_face
     *
     * @param sealFace the value for pump_fa_lan_info.seal_face
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public void setSealFace(String sealFace) {
        this.sealFace = sealFace == null ? null : sealFace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pump_fa_lan_info.dn
     *
     * @return the value of pump_fa_lan_info.dn
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public Float getDn() {
        return dn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pump_fa_lan_info.dn
     *
     * @param dn the value for pump_fa_lan_info.dn
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public void setDn(Float dn) {
        this.dn = dn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pump_fa_lan_info.dn_type
     *
     * @return the value of pump_fa_lan_info.dn_type
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public String getDnType() {
        return dnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pump_fa_lan_info.dn_type
     *
     * @param dnType the value for pump_fa_lan_info.dn_type
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public void setDnType(String dnType) {
        this.dnType = dnType == null ? null : dnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pump_fa_lan_info.pump_source
     *
     * @return the value of pump_fa_lan_info.pump_source
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public String getPumpSource() {
        return pumpSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pump_fa_lan_info.pump_source
     *
     * @param pumpSource the value for pump_fa_lan_info.pump_source
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public void setPumpSource(String pumpSource) {
        this.pumpSource = pumpSource == null ? null : pumpSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pump_fa_lan_info.created_user_id
     *
     * @return the value of pump_fa_lan_info.created_user_id
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pump_fa_lan_info.created_user_id
     *
     * @param createdUserId the value for pump_fa_lan_info.created_user_id
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pump_fa_lan_info.created_time
     *
     * @return the value of pump_fa_lan_info.created_time
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pump_fa_lan_info.created_time
     *
     * @param createdTime the value for pump_fa_lan_info.created_time
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pump_fa_lan_info.updated_user_id
     *
     * @return the value of pump_fa_lan_info.updated_user_id
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public String getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pump_fa_lan_info.updated_user_id
     *
     * @param updatedUserId the value for pump_fa_lan_info.updated_user_id
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public void setUpdatedUserId(String updatedUserId) {
        this.updatedUserId = updatedUserId == null ? null : updatedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pump_fa_lan_info.updated_time
     *
     * @return the value of pump_fa_lan_info.updated_time
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pump_fa_lan_info.updated_time
     *
     * @param updatedTime the value for pump_fa_lan_info.updated_time
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pump_fa_lan_info.is_deleted
     *
     * @return the value of pump_fa_lan_info.is_deleted
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pump_fa_lan_info.is_deleted
     *
     * @param deletedFlag the value for pump_fa_lan_info.is_deleted
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag == null ? null : deletedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pump_fa_lan_info.pv_desc
     *
     * @return the value of pump_fa_lan_info.pv_desc
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public String getPvDesc() {
        return pvDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pump_fa_lan_info.pv_desc
     *
     * @param pvDesc the value for pump_fa_lan_info.pv_desc
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    public void setPvDesc(String pvDesc) {
        this.pvDesc = pvDesc == null ? null : pvDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pump_fa_lan_info
     *
     * @mbg.generated Wed Mar 08 22:20:59 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pvCode=").append(pvCode);
        sb.append(", flangeStandard=").append(flangeStandard);
        sb.append(", flangType=").append(flangType);
        sb.append(", pressure=").append(pressure);
        sb.append(", sealFace=").append(sealFace);
        sb.append(", dn=").append(dn);
        sb.append(", dnType=").append(dnType);
        sb.append(", pumpSource=").append(pumpSource);
        sb.append(", createdUserId=").append(createdUserId);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedUserId=").append(updatedUserId);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", deletedFlag=").append(deletedFlag);
        sb.append(", pvDesc=").append(pvDesc);
        sb.append("]");
        return sb.toString();
    }
}