package com.t.zero.b.i.pump.db.model.auto;

import java.util.ArrayList;
import java.util.List;

public class UnitsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    public UnitsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectnumberIsNull() {
            addCriterion("ProjectNumber is null");
            return (Criteria) this;
        }

        public Criteria andProjectnumberIsNotNull() {
            addCriterion("ProjectNumber is not null");
            return (Criteria) this;
        }

        public Criteria andProjectnumberEqualTo(String value) {
            addCriterion("ProjectNumber =", value, "projectnumber");
            return (Criteria) this;
        }

        public Criteria andProjectnumberNotEqualTo(String value) {
            addCriterion("ProjectNumber <>", value, "projectnumber");
            return (Criteria) this;
        }

        public Criteria andProjectnumberGreaterThan(String value) {
            addCriterion("ProjectNumber >", value, "projectnumber");
            return (Criteria) this;
        }

        public Criteria andProjectnumberGreaterThanOrEqualTo(String value) {
            addCriterion("ProjectNumber >=", value, "projectnumber");
            return (Criteria) this;
        }

        public Criteria andProjectnumberLessThan(String value) {
            addCriterion("ProjectNumber <", value, "projectnumber");
            return (Criteria) this;
        }

        public Criteria andProjectnumberLessThanOrEqualTo(String value) {
            addCriterion("ProjectNumber <=", value, "projectnumber");
            return (Criteria) this;
        }

        public Criteria andProjectnumberLike(String value) {
            addCriterion("ProjectNumber like", value, "projectnumber");
            return (Criteria) this;
        }

        public Criteria andProjectnumberNotLike(String value) {
            addCriterion("ProjectNumber not like", value, "projectnumber");
            return (Criteria) this;
        }

        public Criteria andProjectnumberIn(List<String> values) {
            addCriterion("ProjectNumber in", values, "projectnumber");
            return (Criteria) this;
        }

        public Criteria andProjectnumberNotIn(List<String> values) {
            addCriterion("ProjectNumber not in", values, "projectnumber");
            return (Criteria) this;
        }

        public Criteria andProjectnumberBetween(String value1, String value2) {
            addCriterion("ProjectNumber between", value1, value2, "projectnumber");
            return (Criteria) this;
        }

        public Criteria andProjectnumberNotBetween(String value1, String value2) {
            addCriterion("ProjectNumber not between", value1, value2, "projectnumber");
            return (Criteria) this;
        }

        public Criteria andQIsNull() {
            addCriterion("Q is null");
            return (Criteria) this;
        }

        public Criteria andQIsNotNull() {
            addCriterion("Q is not null");
            return (Criteria) this;
        }

        public Criteria andQEqualTo(String value) {
            addCriterion("Q =", value, "q");
            return (Criteria) this;
        }

        public Criteria andQNotEqualTo(String value) {
            addCriterion("Q <>", value, "q");
            return (Criteria) this;
        }

        public Criteria andQGreaterThan(String value) {
            addCriterion("Q >", value, "q");
            return (Criteria) this;
        }

        public Criteria andQGreaterThanOrEqualTo(String value) {
            addCriterion("Q >=", value, "q");
            return (Criteria) this;
        }

        public Criteria andQLessThan(String value) {
            addCriterion("Q <", value, "q");
            return (Criteria) this;
        }

        public Criteria andQLessThanOrEqualTo(String value) {
            addCriterion("Q <=", value, "q");
            return (Criteria) this;
        }

        public Criteria andQLike(String value) {
            addCriterion("Q like", value, "q");
            return (Criteria) this;
        }

        public Criteria andQNotLike(String value) {
            addCriterion("Q not like", value, "q");
            return (Criteria) this;
        }

        public Criteria andQIn(List<String> values) {
            addCriterion("Q in", values, "q");
            return (Criteria) this;
        }

        public Criteria andQNotIn(List<String> values) {
            addCriterion("Q not in", values, "q");
            return (Criteria) this;
        }

        public Criteria andQBetween(String value1, String value2) {
            addCriterion("Q between", value1, value2, "q");
            return (Criteria) this;
        }

        public Criteria andQNotBetween(String value1, String value2) {
            addCriterion("Q not between", value1, value2, "q");
            return (Criteria) this;
        }

        public Criteria andHIsNull() {
            addCriterion("H is null");
            return (Criteria) this;
        }

        public Criteria andHIsNotNull() {
            addCriterion("H is not null");
            return (Criteria) this;
        }

        public Criteria andHEqualTo(String value) {
            addCriterion("H =", value, "h");
            return (Criteria) this;
        }

        public Criteria andHNotEqualTo(String value) {
            addCriterion("H <>", value, "h");
            return (Criteria) this;
        }

        public Criteria andHGreaterThan(String value) {
            addCriterion("H >", value, "h");
            return (Criteria) this;
        }

        public Criteria andHGreaterThanOrEqualTo(String value) {
            addCriterion("H >=", value, "h");
            return (Criteria) this;
        }

        public Criteria andHLessThan(String value) {
            addCriterion("H <", value, "h");
            return (Criteria) this;
        }

        public Criteria andHLessThanOrEqualTo(String value) {
            addCriterion("H <=", value, "h");
            return (Criteria) this;
        }

        public Criteria andHLike(String value) {
            addCriterion("H like", value, "h");
            return (Criteria) this;
        }

        public Criteria andHNotLike(String value) {
            addCriterion("H not like", value, "h");
            return (Criteria) this;
        }

        public Criteria andHIn(List<String> values) {
            addCriterion("H in", values, "h");
            return (Criteria) this;
        }

        public Criteria andHNotIn(List<String> values) {
            addCriterion("H not in", values, "h");
            return (Criteria) this;
        }

        public Criteria andHBetween(String value1, String value2) {
            addCriterion("H between", value1, value2, "h");
            return (Criteria) this;
        }

        public Criteria andHNotBetween(String value1, String value2) {
            addCriterion("H not between", value1, value2, "h");
            return (Criteria) this;
        }

        public Criteria andTempIsNull() {
            addCriterion("Temp is null");
            return (Criteria) this;
        }

        public Criteria andTempIsNotNull() {
            addCriterion("Temp is not null");
            return (Criteria) this;
        }

        public Criteria andTempEqualTo(String value) {
            addCriterion("Temp =", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempNotEqualTo(String value) {
            addCriterion("Temp <>", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempGreaterThan(String value) {
            addCriterion("Temp >", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempGreaterThanOrEqualTo(String value) {
            addCriterion("Temp >=", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempLessThan(String value) {
            addCriterion("Temp <", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempLessThanOrEqualTo(String value) {
            addCriterion("Temp <=", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempLike(String value) {
            addCriterion("Temp like", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempNotLike(String value) {
            addCriterion("Temp not like", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempIn(List<String> values) {
            addCriterion("Temp in", values, "temp");
            return (Criteria) this;
        }

        public Criteria andTempNotIn(List<String> values) {
            addCriterion("Temp not in", values, "temp");
            return (Criteria) this;
        }

        public Criteria andTempBetween(String value1, String value2) {
            addCriterion("Temp between", value1, value2, "temp");
            return (Criteria) this;
        }

        public Criteria andTempNotBetween(String value1, String value2) {
            addCriterion("Temp not between", value1, value2, "temp");
            return (Criteria) this;
        }

        public Criteria andViscosityIsNull() {
            addCriterion("viscosity is null");
            return (Criteria) this;
        }

        public Criteria andViscosityIsNotNull() {
            addCriterion("viscosity is not null");
            return (Criteria) this;
        }

        public Criteria andViscosityEqualTo(String value) {
            addCriterion("viscosity =", value, "viscosity");
            return (Criteria) this;
        }

        public Criteria andViscosityNotEqualTo(String value) {
            addCriterion("viscosity <>", value, "viscosity");
            return (Criteria) this;
        }

        public Criteria andViscosityGreaterThan(String value) {
            addCriterion("viscosity >", value, "viscosity");
            return (Criteria) this;
        }

        public Criteria andViscosityGreaterThanOrEqualTo(String value) {
            addCriterion("viscosity >=", value, "viscosity");
            return (Criteria) this;
        }

        public Criteria andViscosityLessThan(String value) {
            addCriterion("viscosity <", value, "viscosity");
            return (Criteria) this;
        }

        public Criteria andViscosityLessThanOrEqualTo(String value) {
            addCriterion("viscosity <=", value, "viscosity");
            return (Criteria) this;
        }

        public Criteria andViscosityLike(String value) {
            addCriterion("viscosity like", value, "viscosity");
            return (Criteria) this;
        }

        public Criteria andViscosityNotLike(String value) {
            addCriterion("viscosity not like", value, "viscosity");
            return (Criteria) this;
        }

        public Criteria andViscosityIn(List<String> values) {
            addCriterion("viscosity in", values, "viscosity");
            return (Criteria) this;
        }

        public Criteria andViscosityNotIn(List<String> values) {
            addCriterion("viscosity not in", values, "viscosity");
            return (Criteria) this;
        }

        public Criteria andViscosityBetween(String value1, String value2) {
            addCriterion("viscosity between", value1, value2, "viscosity");
            return (Criteria) this;
        }

        public Criteria andViscosityNotBetween(String value1, String value2) {
            addCriterion("viscosity not between", value1, value2, "viscosity");
            return (Criteria) this;
        }

        public Criteria andInnerpressureIsNull() {
            addCriterion("InnerPressure is null");
            return (Criteria) this;
        }

        public Criteria andInnerpressureIsNotNull() {
            addCriterion("InnerPressure is not null");
            return (Criteria) this;
        }

        public Criteria andInnerpressureEqualTo(String value) {
            addCriterion("InnerPressure =", value, "innerpressure");
            return (Criteria) this;
        }

        public Criteria andInnerpressureNotEqualTo(String value) {
            addCriterion("InnerPressure <>", value, "innerpressure");
            return (Criteria) this;
        }

        public Criteria andInnerpressureGreaterThan(String value) {
            addCriterion("InnerPressure >", value, "innerpressure");
            return (Criteria) this;
        }

        public Criteria andInnerpressureGreaterThanOrEqualTo(String value) {
            addCriterion("InnerPressure >=", value, "innerpressure");
            return (Criteria) this;
        }

        public Criteria andInnerpressureLessThan(String value) {
            addCriterion("InnerPressure <", value, "innerpressure");
            return (Criteria) this;
        }

        public Criteria andInnerpressureLessThanOrEqualTo(String value) {
            addCriterion("InnerPressure <=", value, "innerpressure");
            return (Criteria) this;
        }

        public Criteria andInnerpressureLike(String value) {
            addCriterion("InnerPressure like", value, "innerpressure");
            return (Criteria) this;
        }

        public Criteria andInnerpressureNotLike(String value) {
            addCriterion("InnerPressure not like", value, "innerpressure");
            return (Criteria) this;
        }

        public Criteria andInnerpressureIn(List<String> values) {
            addCriterion("InnerPressure in", values, "innerpressure");
            return (Criteria) this;
        }

        public Criteria andInnerpressureNotIn(List<String> values) {
            addCriterion("InnerPressure not in", values, "innerpressure");
            return (Criteria) this;
        }

        public Criteria andInnerpressureBetween(String value1, String value2) {
            addCriterion("InnerPressure between", value1, value2, "innerpressure");
            return (Criteria) this;
        }

        public Criteria andInnerpressureNotBetween(String value1, String value2) {
            addCriterion("InnerPressure not between", value1, value2, "innerpressure");
            return (Criteria) this;
        }

        public Criteria andOutpressureIsNull() {
            addCriterion("OutPressure is null");
            return (Criteria) this;
        }

        public Criteria andOutpressureIsNotNull() {
            addCriterion("OutPressure is not null");
            return (Criteria) this;
        }

        public Criteria andOutpressureEqualTo(String value) {
            addCriterion("OutPressure =", value, "outpressure");
            return (Criteria) this;
        }

        public Criteria andOutpressureNotEqualTo(String value) {
            addCriterion("OutPressure <>", value, "outpressure");
            return (Criteria) this;
        }

        public Criteria andOutpressureGreaterThan(String value) {
            addCriterion("OutPressure >", value, "outpressure");
            return (Criteria) this;
        }

        public Criteria andOutpressureGreaterThanOrEqualTo(String value) {
            addCriterion("OutPressure >=", value, "outpressure");
            return (Criteria) this;
        }

        public Criteria andOutpressureLessThan(String value) {
            addCriterion("OutPressure <", value, "outpressure");
            return (Criteria) this;
        }

        public Criteria andOutpressureLessThanOrEqualTo(String value) {
            addCriterion("OutPressure <=", value, "outpressure");
            return (Criteria) this;
        }

        public Criteria andOutpressureLike(String value) {
            addCriterion("OutPressure like", value, "outpressure");
            return (Criteria) this;
        }

        public Criteria andOutpressureNotLike(String value) {
            addCriterion("OutPressure not like", value, "outpressure");
            return (Criteria) this;
        }

        public Criteria andOutpressureIn(List<String> values) {
            addCriterion("OutPressure in", values, "outpressure");
            return (Criteria) this;
        }

        public Criteria andOutpressureNotIn(List<String> values) {
            addCriterion("OutPressure not in", values, "outpressure");
            return (Criteria) this;
        }

        public Criteria andOutpressureBetween(String value1, String value2) {
            addCriterion("OutPressure between", value1, value2, "outpressure");
            return (Criteria) this;
        }

        public Criteria andOutpressureNotBetween(String value1, String value2) {
            addCriterion("OutPressure not between", value1, value2, "outpressure");
            return (Criteria) this;
        }

        public Criteria andGasIsNull() {
            addCriterion("Gas is null");
            return (Criteria) this;
        }

        public Criteria andGasIsNotNull() {
            addCriterion("Gas is not null");
            return (Criteria) this;
        }

        public Criteria andGasEqualTo(String value) {
            addCriterion("Gas =", value, "gas");
            return (Criteria) this;
        }

        public Criteria andGasNotEqualTo(String value) {
            addCriterion("Gas <>", value, "gas");
            return (Criteria) this;
        }

        public Criteria andGasGreaterThan(String value) {
            addCriterion("Gas >", value, "gas");
            return (Criteria) this;
        }

        public Criteria andGasGreaterThanOrEqualTo(String value) {
            addCriterion("Gas >=", value, "gas");
            return (Criteria) this;
        }

        public Criteria andGasLessThan(String value) {
            addCriterion("Gas <", value, "gas");
            return (Criteria) this;
        }

        public Criteria andGasLessThanOrEqualTo(String value) {
            addCriterion("Gas <=", value, "gas");
            return (Criteria) this;
        }

        public Criteria andGasLike(String value) {
            addCriterion("Gas like", value, "gas");
            return (Criteria) this;
        }

        public Criteria andGasNotLike(String value) {
            addCriterion("Gas not like", value, "gas");
            return (Criteria) this;
        }

        public Criteria andGasIn(List<String> values) {
            addCriterion("Gas in", values, "gas");
            return (Criteria) this;
        }

        public Criteria andGasNotIn(List<String> values) {
            addCriterion("Gas not in", values, "gas");
            return (Criteria) this;
        }

        public Criteria andGasBetween(String value1, String value2) {
            addCriterion("Gas between", value1, value2, "gas");
            return (Criteria) this;
        }

        public Criteria andGasNotBetween(String value1, String value2) {
            addCriterion("Gas not between", value1, value2, "gas");
            return (Criteria) this;
        }

        public Criteria andDepthIsNull() {
            addCriterion("Depth is null");
            return (Criteria) this;
        }

        public Criteria andDepthIsNotNull() {
            addCriterion("Depth is not null");
            return (Criteria) this;
        }

        public Criteria andDepthEqualTo(String value) {
            addCriterion("Depth =", value, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthNotEqualTo(String value) {
            addCriterion("Depth <>", value, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthGreaterThan(String value) {
            addCriterion("Depth >", value, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthGreaterThanOrEqualTo(String value) {
            addCriterion("Depth >=", value, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthLessThan(String value) {
            addCriterion("Depth <", value, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthLessThanOrEqualTo(String value) {
            addCriterion("Depth <=", value, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthLike(String value) {
            addCriterion("Depth like", value, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthNotLike(String value) {
            addCriterion("Depth not like", value, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthIn(List<String> values) {
            addCriterion("Depth in", values, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthNotIn(List<String> values) {
            addCriterion("Depth not in", values, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthBetween(String value1, String value2) {
            addCriterion("Depth between", value1, value2, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthNotBetween(String value1, String value2) {
            addCriterion("Depth not between", value1, value2, "depth");
            return (Criteria) this;
        }

        public Criteria andNpshaIsNull() {
            addCriterion("NPSHa is null");
            return (Criteria) this;
        }

        public Criteria andNpshaIsNotNull() {
            addCriterion("NPSHa is not null");
            return (Criteria) this;
        }

        public Criteria andNpshaEqualTo(String value) {
            addCriterion("NPSHa =", value, "npsha");
            return (Criteria) this;
        }

        public Criteria andNpshaNotEqualTo(String value) {
            addCriterion("NPSHa <>", value, "npsha");
            return (Criteria) this;
        }

        public Criteria andNpshaGreaterThan(String value) {
            addCriterion("NPSHa >", value, "npsha");
            return (Criteria) this;
        }

        public Criteria andNpshaGreaterThanOrEqualTo(String value) {
            addCriterion("NPSHa >=", value, "npsha");
            return (Criteria) this;
        }

        public Criteria andNpshaLessThan(String value) {
            addCriterion("NPSHa <", value, "npsha");
            return (Criteria) this;
        }

        public Criteria andNpshaLessThanOrEqualTo(String value) {
            addCriterion("NPSHa <=", value, "npsha");
            return (Criteria) this;
        }

        public Criteria andNpshaLike(String value) {
            addCriterion("NPSHa like", value, "npsha");
            return (Criteria) this;
        }

        public Criteria andNpshaNotLike(String value) {
            addCriterion("NPSHa not like", value, "npsha");
            return (Criteria) this;
        }

        public Criteria andNpshaIn(List<String> values) {
            addCriterion("NPSHa in", values, "npsha");
            return (Criteria) this;
        }

        public Criteria andNpshaNotIn(List<String> values) {
            addCriterion("NPSHa not in", values, "npsha");
            return (Criteria) this;
        }

        public Criteria andNpshaBetween(String value1, String value2) {
            addCriterion("NPSHa between", value1, value2, "npsha");
            return (Criteria) this;
        }

        public Criteria andNpshaNotBetween(String value1, String value2) {
            addCriterion("NPSHa not between", value1, value2, "npsha");
            return (Criteria) this;
        }

        public Criteria andNpshrIsNull() {
            addCriterion("NPSHr is null");
            return (Criteria) this;
        }

        public Criteria andNpshrIsNotNull() {
            addCriterion("NPSHr is not null");
            return (Criteria) this;
        }

        public Criteria andNpshrEqualTo(String value) {
            addCriterion("NPSHr =", value, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrNotEqualTo(String value) {
            addCriterion("NPSHr <>", value, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrGreaterThan(String value) {
            addCriterion("NPSHr >", value, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrGreaterThanOrEqualTo(String value) {
            addCriterion("NPSHr >=", value, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrLessThan(String value) {
            addCriterion("NPSHr <", value, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrLessThanOrEqualTo(String value) {
            addCriterion("NPSHr <=", value, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrLike(String value) {
            addCriterion("NPSHr like", value, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrNotLike(String value) {
            addCriterion("NPSHr not like", value, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrIn(List<String> values) {
            addCriterion("NPSHr in", values, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrNotIn(List<String> values) {
            addCriterion("NPSHr not in", values, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrBetween(String value1, String value2) {
            addCriterion("NPSHr between", value1, value2, "npshr");
            return (Criteria) this;
        }

        public Criteria andNpshrNotBetween(String value1, String value2) {
            addCriterion("NPSHr not between", value1, value2, "npshr");
            return (Criteria) this;
        }

        public Criteria andPowerThisIsNull() {
            addCriterion("power_this is null");
            return (Criteria) this;
        }

        public Criteria andPowerThisIsNotNull() {
            addCriterion("power_this is not null");
            return (Criteria) this;
        }

        public Criteria andPowerThisEqualTo(String value) {
            addCriterion("power_this =", value, "powerThis");
            return (Criteria) this;
        }

        public Criteria andPowerThisNotEqualTo(String value) {
            addCriterion("power_this <>", value, "powerThis");
            return (Criteria) this;
        }

        public Criteria andPowerThisGreaterThan(String value) {
            addCriterion("power_this >", value, "powerThis");
            return (Criteria) this;
        }

        public Criteria andPowerThisGreaterThanOrEqualTo(String value) {
            addCriterion("power_this >=", value, "powerThis");
            return (Criteria) this;
        }

        public Criteria andPowerThisLessThan(String value) {
            addCriterion("power_this <", value, "powerThis");
            return (Criteria) this;
        }

        public Criteria andPowerThisLessThanOrEqualTo(String value) {
            addCriterion("power_this <=", value, "powerThis");
            return (Criteria) this;
        }

        public Criteria andPowerThisLike(String value) {
            addCriterion("power_this like", value, "powerThis");
            return (Criteria) this;
        }

        public Criteria andPowerThisNotLike(String value) {
            addCriterion("power_this not like", value, "powerThis");
            return (Criteria) this;
        }

        public Criteria andPowerThisIn(List<String> values) {
            addCriterion("power_this in", values, "powerThis");
            return (Criteria) this;
        }

        public Criteria andPowerThisNotIn(List<String> values) {
            addCriterion("power_this not in", values, "powerThis");
            return (Criteria) this;
        }

        public Criteria andPowerThisBetween(String value1, String value2) {
            addCriterion("power_this between", value1, value2, "powerThis");
            return (Criteria) this;
        }

        public Criteria andPowerThisNotBetween(String value1, String value2) {
            addCriterion("power_this not between", value1, value2, "powerThis");
            return (Criteria) this;
        }

        public Criteria andLevelMoterIsNull() {
            addCriterion("level_moter is null");
            return (Criteria) this;
        }

        public Criteria andLevelMoterIsNotNull() {
            addCriterion("level_moter is not null");
            return (Criteria) this;
        }

        public Criteria andLevelMoterEqualTo(String value) {
            addCriterion("level_moter =", value, "levelMoter");
            return (Criteria) this;
        }

        public Criteria andLevelMoterNotEqualTo(String value) {
            addCriterion("level_moter <>", value, "levelMoter");
            return (Criteria) this;
        }

        public Criteria andLevelMoterGreaterThan(String value) {
            addCriterion("level_moter >", value, "levelMoter");
            return (Criteria) this;
        }

        public Criteria andLevelMoterGreaterThanOrEqualTo(String value) {
            addCriterion("level_moter >=", value, "levelMoter");
            return (Criteria) this;
        }

        public Criteria andLevelMoterLessThan(String value) {
            addCriterion("level_moter <", value, "levelMoter");
            return (Criteria) this;
        }

        public Criteria andLevelMoterLessThanOrEqualTo(String value) {
            addCriterion("level_moter <=", value, "levelMoter");
            return (Criteria) this;
        }

        public Criteria andLevelMoterLike(String value) {
            addCriterion("level_moter like", value, "levelMoter");
            return (Criteria) this;
        }

        public Criteria andLevelMoterNotLike(String value) {
            addCriterion("level_moter not like", value, "levelMoter");
            return (Criteria) this;
        }

        public Criteria andLevelMoterIn(List<String> values) {
            addCriterion("level_moter in", values, "levelMoter");
            return (Criteria) this;
        }

        public Criteria andLevelMoterNotIn(List<String> values) {
            addCriterion("level_moter not in", values, "levelMoter");
            return (Criteria) this;
        }

        public Criteria andLevelMoterBetween(String value1, String value2) {
            addCriterion("level_moter between", value1, value2, "levelMoter");
            return (Criteria) this;
        }

        public Criteria andLevelMoterNotBetween(String value1, String value2) {
            addCriterion("level_moter not between", value1, value2, "levelMoter");
            return (Criteria) this;
        }

        public Criteria andFrequencyIsNull() {
            addCriterion("frequency is null");
            return (Criteria) this;
        }

        public Criteria andFrequencyIsNotNull() {
            addCriterion("frequency is not null");
            return (Criteria) this;
        }

        public Criteria andFrequencyEqualTo(String value) {
            addCriterion("frequency =", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyNotEqualTo(String value) {
            addCriterion("frequency <>", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyGreaterThan(String value) {
            addCriterion("frequency >", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyGreaterThanOrEqualTo(String value) {
            addCriterion("frequency >=", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyLessThan(String value) {
            addCriterion("frequency <", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyLessThanOrEqualTo(String value) {
            addCriterion("frequency <=", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyLike(String value) {
            addCriterion("frequency like", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyNotLike(String value) {
            addCriterion("frequency not like", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyIn(List<String> values) {
            addCriterion("frequency in", values, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyNotIn(List<String> values) {
            addCriterion("frequency not in", values, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyBetween(String value1, String value2) {
            addCriterion("frequency between", value1, value2, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyNotBetween(String value1, String value2) {
            addCriterion("frequency not between", value1, value2, "frequency");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table units
     *
     * @mbg.generated do_not_delete_during_merge Sat Feb 25 14:14:00 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table units
     *
     * @mbg.generated Sat Feb 25 14:14:00 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}